### ISSUE TITLE
pop3test MITM warning on v2.3.16

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1159]
From: [Matt Selsky](selsky@columbia.edu)
Bugzilla-Id: 3242
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
This appears to only be an issue when SASL auth succeeds with a mech that has a security layer, but the Inbox fails to open (e.g. already open or too frequent logins).  The solution is to hold off setting the SSF in the server-side SASL context until the mailbox is opened.

Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/50e7872df3b98d7d7e3f3e335d17c8833e8dd211
