### ISSUE TITLE
Default specialusealways to on

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1556]
From: [Greg Banks](gnb@fastmail.fm)
Bugzilla-Id: 3689
Version: 2.5.x (next)
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by rsto** [comment]
[RFC 6154](https://tools.ietf.org/html/rfc6154#section-2) section 2 states that 

> The extended LIST command MAY return SPECIAL-USE attributes even if the client does not specify the return option.

so we may indeed return special-use flags for any LIST command. However, I don't have an iOS device to check if versions later of 2012 pass the SPECIAL-USE return option properly. The [IMAP Wiki](https://www.imapwiki.org/SpecialUse) isn't of much help to determine this either.

@brong do you find by chance an iOS LIST command in the logs, where we can determine if the client passes the SPECIAL-USE return option?

**Comment by rsto** [comment]
[RFC 6154](https://tools.ietf.org/html/rfc6154#section-2) states that

> The extended LIST command MAY return SPECIAL-USE attributes even if the client does not specify the return option.

Plus: we haven't seen any clients complain at FastMail since specialusealways is set to on.

That's good enough reason to change the default to 'on', and this is done in https://github.com/cyrusimap/cyrus-imapd/commit/9f98ad5db77ae95e70fb401ed83d23556bd4db04

**Comment by nicolan** [comment]
@rsto What are the implications of swapping this for people upgrading versions who don't have this explicitly defined? Plus also: release notes.

**Comment by rsto** [comment]
@nicola installations that had set this value to false (or not at all) might now experience an issue, if old, broken clients can't handle the RFC-compliant answer. IMHO the chances for this are slim, but surely it's possible.

Do you mean I should update the release notes?

**Comment by nicolan** [comment]
Are you saying that specialusealways shouldn't actually even be an option? In fact that there is no real reason (any more) to have this switched off? I love removing options that should just be regular functionality and not a toggle.

Yes, I think we need release notes in case people had this set to false or unset, so they know that it's now changed.

**Comment by rsto** [comment]
No, we can't remove that option: installations that want to keep using clients that can't handle specialuse flags will want to disable 'specialusealways'. We just want to enable it by default, since it's OK by the RFC and can solve hiccups with older iOS clients that in fact, expect it to be on.

I'll be happy to write a short note in the release notes, but how to do that?

**Comment by nicolan** [comment]
I made some placeholder release notes! docsrc/imap/download/release-notes/3.1/x/3.1.0-dev.rst

It should be obvious where your config changes goes. :)

**Comment by rsto** [comment]
thanks @nicolan . done in https://github.com/cyrusimap/cyrus-imapd/commit/3878ee086f40920df59372f60b1c8eca49df0b10
