### ISSUE TITLE
pidfile support for sync_client

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1623]
From: [Michael Menge](michael.menge@zdv.uni-tuebingen.de)
Bugzilla-Id: 3815
Version: 2.4.x (next)
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by elliefm** [comment]
Multiple sync_clients can be legitimately be running at the same time (including in rolling mode, if they're each processing a different channel's log), so preventing them from blatting over each other's pid file could be interesting.  Maybe a filename like `sync_client-<channel>.pid` would be a start, but this needs further thought.

The `-p` switch is already used for setting the destination partition (in user/mailbox modes)

**Comment by elliefm** [comment]
Reading between the lines, maybe the desire for having a rolling sync_client pid file is so an init script can shut it down at the same time as master.  In which case, this can be achieved just by running your rolling sync_clients from the DAEMON section of cyrus.conf, rather than the START section.
