### ISSUE TITLE
log username on failed SASL logins

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1679]
From: [Wolfgang Breyha](wbreyha@gmx.net)
Bugzilla-Id: 3825
Version: 2.4.17
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by elliefm** [comment]
@MASHtm do you still use/maintain this patch?  It doesn't look like it's ever been applied upstream

**Comment by MASHtm** [comment]
Yes I do actually;-) Latest version is:

[cyrus256-badlogin_user.patch.txt](https://github.com/cyrusimap/cyrus-imapd/files/1204292/cyrus256-badlogin_user.patch.txt)

**Comment by elliefm** [comment]
Yikes, finally merged this to master! 😅

I've had a think about it, and I won't put it on the 3.0 branch, because of the format changes to the string -- just in case people have something monitoring these logs that they don't want suddenly breaking.  If 3.0 users want it, it's easy enough to just cherry-pick b40d3f06b
