### ISSUE TITLE
SELECT writes .lock file for unknown/inexistent mailboxes

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1692]
From: [Wolfgang Breyha](wbreyha@gmx.net)
Bugzilla-Id: 3844
Version: 2.4.17
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by rsto** [comment]
We debated this over the last few days, but don't see the need to change this. Mailbox locks are on a bunch of critical codepaths and these stale lock files have not shown once to be an operational issue.

I updated the docs accordingly: https://github.com/cyrusimap/cyrus-imapd/commit/922319da0240acb01ba9198edf1a0f94472dae33

We'll be happy to reconsider changing the lock mechanism if the current approach turns out to be of real concern.
