### ISSUE TITLE
cyr_expire only accepts internal mailbox naming

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1699]
From: [Rudy Gevaert](rudy.gevaert@ugent.be)
Bugzilla-Id: 3854
Version: 2.4.17
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by karagian** [comment]
Not sure if I should open a new bug, but I noticed the same problem with "quota" command in the 3.0.x version.

**Comment by elliefm** [comment]
I don't think we want to change behaviour on 3.0, but this makes sense for master.

FastMail infrastructure will need coordination because we have scripts that run off the back of these commands.

I'm 80% sure there's another open issue about the same thing, opened by @brong I believe?

**Comment by karagian** [comment]
Hi Ellie! Thank you for taking a look into this. The behavior of these command line tools changes in versions 2.5.x and 3.0.x. Administrators will only bump into this bug only if **unixhierarchysep** is set and will not be able to use these commands properly, unless they perform a conversion in their scripts of the mailbox names coming from other command line tools... The bug fix will save them from this trouble.
If unixhierarchysep is not set, the bug is never noticed and scripts using these commands do not need to change anything, since they already handle mailbox names in the internal format.

**Comment by elliefm** [comment]
Ah thanks, that's very helpful!
