### ISSUE TITLE
Linux, OpenVZ: stops listening on ports when low memory

### ISSUE THREAD

**Issue by asy972** [cyrusimap/cyrus-imapd#1751]
Hello.

I attempt to use Cyrus-IMAP (2.5.9 now) in OpenVZ container. Some time container reaches kmemsize barrier limit. Listener stops listen port if it used in this time. All other listeners continue working (including similar on IP another version). Often used pop3/IPv4 and It disconnects:
```
0.0.0.0:143    LISTEN  1048/cyrus-master
0.0.0.0:2000   LISTEN  1048/cyrus-master
127.0.0.1:466  LISTEN  1048/cyrus-master
127.0.0.1:24   LISTEN  1048/cyrus-master
:::110         LISTEN  1048/cyrus-master
:::143         LISTEN  1048/cyrus-master
:::2000        LISTEN  1048/cyrus-master
::1:466        LISTEN  1048/cyrus-master
::1:24         LISTEN  1048/cyrus-master
```

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
