### ISSUE TITLE
Update Xapian to 1.4.2

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1761]
Xapian upstream have released 1.4.2, we need to rebase our Xapian branch on top of that

**Comment by rsto** [comment]
Rebased our cyrus fork of cyruslibs/xapian against latest upstream master.

Removed commit 'queryinternal: initialize old_in_synonym to false to avoid GCC error' (3270faefd7cf6bb446e6c658900f4f2d944c4188) from the cyrus fork since it got fixed upstream.

@brong: ready to update cyruslibs submodules if the build is OK on your machine

**Comment by rsto** [comment]
BTW I see that neither https://github.com/rsto/xapian/commit/e432d7914e8b97f41b114980d92deb9fd1fc72e2 (the memory corruption fix) nor https://github.com/rsto/xapian/commit/d9e722851330111e995f56b96a102308e6adef48 (fix confusing indent) show up in the commit history, but their code seemingly is merged. Any ideas why?

**Comment by rsto** [comment]
We are running this in cyruslibs since two weeks now. Guess it's OK to close, as we'll need to reevaluate the soon-to-be-updated cyruslibs for snippets anyways.
