### ISSUE TITLE
ctl_mboxlist segmentation faults with ACLs for groups containing space

### ISSUE THREAD

**Issue by karagian** [cyrusimap/cyrus-imapd#1851]
Hi all,

I was testing the upgrade to the latest stable version 2.5.10 and had issues with ACLs for groups containing spaces. The group is an existing group on LDAP authentication backend.

Setting the ACL is possible, and cyrus responds with "OK completed":

```
>00000 GETACL "Public Mailbox"
<* ACL "Public Mailbox" anyone lrs
>00001 SETACL "Public Mailbox" "group:Domain Users" lrs
<00001 OK Completed
```
But after that, the ctl_mboxlist command segfaults at the point of displaying the mailbox with the above ACL!
Furthermore, after setting the ACL it is not possible to unset it or even read it back:

```
>00002 SETACL "Public Mailbox" "group:Domain Users" ""
<00002 NO Invalid identifier
>00003 GETACL "Public Mailbox"
<00003 NO Invalid identifier
```

The cyrus.header file in the mailbox folder seems to contain the ACL:
```
/var/spool/imap/Public Mailbox# cat cyrus.header 
Cyrus mailbox header
"The best thing about this system was that it had lots of goals."
        --Jim Morris on Andrew
        1cb22aac-83e6-444a-890b-321fb4f23f4b

anyone  lrs     group:Domain Users      lrs
```

I saw this problem also mentioned on info-cyrus mailing list back in 2015 here:
https://lists.andrew.cmu.edu/pipermail/info-cyrus/2015-November/038650.html

Earlier versions of cyrus (2.4.x) did not have this issue. I tested it and worked without a problem.

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
