### ISSUE TITLE
Annotations: remove getannotation (non-RFC)

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1858]
We still support the non-RFC early draft version of the annotation interface.  It's making all the internals more complex, so just remove it first, then refactor internals to remove its assumptions

**Comment by rsto** [comment]
Had prototyped this but it turns out that GETANNOTATION/SETANNOTATION is more deeply integrated in Cyrus than thought:

- IMAP proxy uses it to proxy annotation fetches/stores
- STORE syntax supports experimental RFC 5257, which again uses the legacy SETANNOTATION format

A bunch of Cassandane tests and most probably custom installations build on STORE to set annotations, so we can't just throw out the code for SETANNOTATION.

Suggest a phased approach: first, get rid of the legacy commands in the proxy. Then set a clear sunset deadline for STORE where installations have to adapt.

**Comment by rsto** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/26fbf999312d03d8f85bbaa6bbf450518efea28a
