### ISSUE TITLE
Change Xapian indexing for headers to be STEM_NONE

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1861]
We discussed this on slack recently.  We want STEM_SOME for BODY and Subject, but STEM_NONE for everything else.  Certainly not STEM_ALL for any of it.

We should fix this for 3.0, so it's all good for both JMAP and the future.  We'll still need to support both v2 and v3 indexes for FastMail I guess, and maybe we'll need to fix to the compact code to only merge indexes which are both in the same format, otherwise reindex the ones that are in the older format.

**Comment by rsto** [comment]
The version upgrade for Xapian stemming prefix is pushed to master: https://github.com/cyrusimap/cyrus-imapd/commit/c966d3e327376933080a2977c1da4fddcdb776ea . This is an uncritical commit, since existing dbs are left untouched, but new dbs will use the latest stemming scheme.

However, there's another commit https://github.com/rsto/cyrus-imapd/commit/f3be09fe7d86a3c707fdf7fee6de7b95ebb8bf35  in my own fork that:
- detects legacy stemmed databases before compression
- wipes their contents
- reindexes them with the mailbox contents.

I've tested this locally, but could you please run this in your dev environment as well?

**Comment by rsto** [comment]
Thanks for the code review. I've uploaded a new patch at https://github.com/rsto/cyrus-imapd/commit/a579ffaef619fac96f4e8044971e76c7964ef324

**Comment by rsto** [comment]
This landed in 3.0.
