### ISSUE TITLE
JMAP support with vanilla Xapian?

### ISSUE THREAD

**Issue by bosim** [cyrusimap/cyrus-imapd#1877]
I am trying to package cyrus-imapd 3.0.0 for openSUSE and saw the released version of Xapian is no good, it seems just to be related to CJK support. Would it be possible to run cyrus-imapd on the released version of Xapian ignoring CJK related handling?

**Comment by rsto** [comment]
As it currently stands: no, because Cyrus compilation would break with missing the CJK_WORDS flag in Xapian.

But it should be doable with autoconf to distinguish between CJK-word enabled Xapians and vanilla Xapian. At minimum you would need to package with Xapian 1.4, since Cyrus build on its snippet generation. I'll look into this tomorrow and if if works out, we might schedule this for 3.0.1.

We are trying to get CJK-word break into Xapian upstream, but didn't manage to do so for 3.0.0. The related PR is at https://github.com/xapian/xapian/pull/114

**Comment by bosim** [comment]
@rsto Thanks a lot for looking into it. It would be great if you could add it as a flag for autoconf.

**Comment by rsto** [comment]
@bosim I've just pushed https://github.com/cyrusimap/cyrus-imapd/commit/96f85a68768cdfca99645ddc18eafadf2ccf3d78 to master and the [3.0 branch](https://github.com/cyrusimap/cyrus-imapd/tree/cyrus-imapd-3.0).

There's no autoconf flag to be set, the configure script will check if you build against vanilla Xapian or the cyruslibs fork. The only caveat is to make sure that you use the right config executable: `xapian-config-1.5` for cyruslibs, `xapian-config` for vanilla.

I'll leave this issue open until I get your OK that this works out for you.

**Comment by bosim** [comment]
@rsto Thanks a lot for the commit worked out like a charm: https://build.opensuse.org/package/show/home:bosim/cyrus-imapd

I had to change the return value of stem_version_set to void since suse's post build checker is quite picky:

 ```
diff --git a/imap/xapian_wrap.cpp b/imap/xapian_wrap.cpp
index 1edf38149..2a174ca68 100644
--- a/imap/xapian_wrap.cpp
+++ b/imap/xapian_wrap.cpp
@@ -256,7 +256,7 @@ static int stem_version_get(Xapian::Database *database)
     return version;
 }
 
-static int stem_version_set(Xapian::WritableDatabase *database, int version)
+static void stem_version_set(Xapian::WritableDatabase *database, int version)
 {
     std::ostringstream convert;
     convert << version;
```

Not sure if it is the plan for the function to return something otherwise I might be a proposed change.

Again, thanks for your fast fix, will start playing with jmap as soon as time permits.

Bo
