### ISSUE TITLE
Makefile.am: Redundant linking in imap/httpd and imap/libcyrus_imap

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1893]
The file `imap/ical_support.c` is included in `imap/libcyrus_imap` and in `imap/httpd`, which links also with `imap/ical_support.c` .  There is no point to link `ical_support.c` in both `imap/libcyrus_imap` and `imap/httpd` and link `imap/httpd` once again with `libcyrus_imap`.

Likewise for `imap/caldav_db.c` and `imap/vcard_support.c`.

There is no point to include `imap/dav_util.h` in `EXTRA_DIST`, as it is part of `imap_libcyrus_imap_la_SOURCES`.

**Comment by elliefm** [comment]
The seemingly redundant linkage in httpd is needed to support -Wl,--as-needed linkage

**Comment by dilyanpalauzov** [comment]
What makes imap/ical_support.c, imap/caldav_db.c or imap/vcard_support.c special in regards to -Wl,--as-needed?

How can I reproduce the problems -Wl,--as-needed causes?  LDFLAGS="-Wl,--as-needed" make forks for me.

What about imap/dav_util.h?

**Comment by elliefm** [comment]
With -Wl,--as-needed, symbols are only included if they've been seen to be used earlier in linking process (this is a simplification but it'll do).

When libcyrus_imap is built, only the symbols from ical_support.c that libcyrus_imap itself needs get included.  But httpd needs symbols from ical_support.c that do not get included in this way.  So it needs to (seemingly redundantly) link ical_support.c itself, in order to have access to those.

To reproduce it, try cleaning your source tree and then `./configure CFLAGS="-Wl,--as-needed $CFLAGS" ...` and then run make

**Comment by dilyanpalauzov** [comment]
`-Wl,--as-needed` has impact only in on the `DT_NEEDED` mentioned libraries in the `.dynamic` section.  So it affects which libraries are loaded, when a library/executable is started, but not which symbols a library exposes.

`#define EXPORTED __attribute__((__visibility__("default")))`, `#define HIDDEN __attribute__((__visibility__("hidden")))` together with `-fvisibility=hidden` on the other handq dictate which symbols a library exports.

So adding `EXPORTED` before the definitions of `icalproperty_get_datetimeperiod`, `icalcomponent_myforeach` and others will export the symbols from libcyrus_imap and there will be no need to link ical_support.c in httpd, too.

Once again, `imap/dav_util.h` in `EXTRA_DIST` is redundant, as it is mentioned by `imap_libcyrus_imap_la_SOURCES`.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/00998a965b47898116179a3785e64378c2017858
