### ISSUE TITLE
Docs: Add note to upgrade docs about increased memory usage for upgrades from 2.3

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#1937]
For those upgrading from 2.3, it is worth noting that by design, cyrus uses more memory.

Selected mailboxes use a lot more memory intentionally to get faster performance and more accurate standards compliance

**Comment by postilion** [comment]
@nicolan I'm not quite sure where to put this.  Sounds like something that should be in a release note, but at what point was this change introduced?  Given what @brong said on conference call, this is a delta-v2.3 issue, so should be covered in 2.4 or 2.5 docs.

I can craft language to explain it, but I just don't know where that language should go.

**Comment by nicolan** [comment]
Rats. I was hoping you'd have a magical cunning plan because I had the same set of thoughts with no clear conclusion. 

I guess it needs to go in the 2.4, 2.5 docs. And in the 3.0 release notes and in the upgrade guide as  a few folks will want to just go straight to the latest. (which says "asset" to me)

**Comment by elliefm** [comment]
I'm reluctant to modify release notes after the fact too much, because it feels like the sort of thing people expect to not change over time...

That said, I think the 2.5.0 (specifically) release notes had an upgrade guide of sorts (all the subsequent 2.5.x release notes refer back to it), so maybe it could be mentioned in there.  And also in the 3.0 upgrade guide.

We can't really put this into 2.4 docs without doing a new 2.4.x release, since we don't publish 2.4 docs from sphinx.  I don't really expect this to be a concern, because in 2017 I don't really expect people to be upgrading _to_ 2.4.x...
