### ISSUE TITLE
Fix use of sidebar when pulling in imapd.conf blobs

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#1938]
We use a sphinx sidebar to show imapd.conf entries in line where they're referenced in config/install guides (see jmap).

Except that what we pull in to show a user is the config defaults, which almost always isn't what we need a user to set. This is confusing!

Options:

- Put a note in, at the top of each affected sidebar saying "these are the defaults, you need to adjust based on what's in the text"
- Stop using the sidebar and make it into a deep link into the man page instead, so it's obvious we are showing the config file defaults.
- Change the manpage source, so the format is different, with the default not listed against the config name directly.
- Other?

**Comment by postilion** [comment]
@nicolan Now you're just being petty & mean. :-)
I don't know anything about the use of sidebar, or how it gets setup.  I can see your point, but since the text we're using derives from /lib/imapoptions, and that is _supposed_ to cite the default setting, we cannot change the source.  I think your first option is the best, but I don't know what to change to effect that.  Can you shed some light on "sidebar"?

**Comment by nicolan** [comment]
Fixed in above mentioned commits.
