### ISSUE TITLE
getaddrinfo errors in 2.4.19 - FreeBSD

### ISSUE THREAD

**Issue by wtps0n** [cyrusimap/cyrus-imapd#1976]
1. Environment:
freebsd 11.0-stable and 10..3-stable. Both amd64.

2. Latest cyrus-imapd build. You can check logs from compilation (with clang):
http://uld.bsdserwis.com/11x64-cyrus-imapd24-2.4.19.log
http://uld.bsdserwis.com/10x64-cyrus-imapd24-2.4.19.log
Options which where chosen: BDB, IDLED and SNMP. No murder (it is small server so I don't need it).

3. on postfix side server uses /usr/local/cyrus/bin/deliver to put emails to mailboxes. I can find use of lmtpunix in logfiles (lmtpunix is default cyrus.conf entry).

4. emails can not be delivered, because in logfiles I found such entries:
 - getaddrinfo(HM-^EŰt HM-^KM-^MM-^Hţ˙˙Ć^A) failed: hostname nor servname provided, or not known
 - getaddrinfo(`ş˙˙˙^?) failed: hostname nor servname provided, or not known
 - getaddrinfo() failed: hostname nor servname provided, or not known

5. Even if I change to use lmtp (via localhost inet socket) the same errors appear in logs. And of course email postfix complains about temporary errors.

6. Till latest upgrade there were no such problems and deliver/lmtpd works without any errors.

7. Maybe I've mde some configuration mistake which is critical from latest version? or maybe I should add some /etc/hosts or local dns entries? How to found why lmtpd (deliver) wants to check dns and for which address?

8. I've checked changelog of 2.4.19 and there is comment about backport code from 2.5.x about lmtpd and mupd. Can it be a clue?

Thanks a lot for any suggestions to find correct solution of this issue.

**Comment by wtps0n** [comment]
OK, so it seems it is not FreeBSD specific. FresBSD port maintainer helped me to find the problem. And I hope it will be more clear what's going on:

----------------------------------------- snip --------------------------------------------------
It seems the message comes from lmtpd but very strange to me.
The message is issued by imap/backend.c:backend_connect().
The sequence is as follows:

  imap/lmtpd.c:deliver()
    |
    +--> imap/lmtpd.c:deliver_remote()
           |
           +--> imap/proxy.c:proxy_findserver()
                  |
                  +--> imap/backend.c:backend_connect()

I believe deliver_local() should be called instead of deliver_remote()
with at least my setup.
I think lmtpd fails to detect local mailbox then try to use proxy wrongly.
----------------------------------------- snip --------------------------------------------------

So can you give some advice how to "force" lmtpd to deliver locally instead of remote? Or maybe I should turn on "murder support"?

Any suggestions?

**Comment by elliefm** [comment]
It's weird that it's trying to `deliver_remote()` if you're not using a murder setup.  It looks like it's winding up with uninitialised junk in the "server" field, and that's why the getaddrinfo() errors are full of gibberish.

@ksmurchison, this looks like it might be related to b2dab34, do you have any insight here?  `mlookup()` tries to carve a server value out of mbentry.partition if the mbtype is MB_REMOTE, so maybe that flag is being set inappropriately, or the mbentry.partition field contains junk in some case?

**Comment by ksmurchison** [comment]
@elliefm  I will have to take a look.  I certainly don't remember the details of the referenced commit

**Comment by wtps0n** [comment]
Sorry, for late response. Someone found resolve of this issue - you can check yourself: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219494

Greetings,

**Comment by elliefm** [comment]
The issue discussed in that thread has been fixed in git, but the patch that fixes it won't resolve your issue I don't think.  It's for a slightly different code path.

**Comment by elliefm** [comment]
Actually on second thought, I think it will.  This is the patch: 129d3ae

**Comment by ajaysusarla** [comment]
@wtps0n, as @elliefm mentioned, this most likely is fixed by the commit https://github.com/cyrusimap/cyrus-imapd/commit/129d3aedbba82d6457fc7cbd436e68f278e0628b on `2.4`. 
The patch in the bug report you mentioned: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219494 does pretty much the same thing, initialise the variables `server` properly. The commit https://github.com/cyrusimap/cyrus-imapd/commit/129d3aedbba82d6457fc7cbd436e68f278e0628b contains a lot more of such initialisations.
I will close this issue, please feel free to reopen it if you are still facing the issue.
Thanks for your time @wtps0n.
