### ISSUE TITLE
JMAP: not returning "name" for some attachments

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1989]
------=_NextPart_000_0015_01D2D2E9.72DB18E0
Content-Type: image/jpeg;
        name="image003.jpg"
Content-Transfer-Encoding: base64
Content-ID: <image003.jpg@01D2D2E9.724E9050>

/9j/

This isn't getting a "name" field, maybe due to not having a Content-Disposition, maybe due to wrapping.  Needs to be fixed.

**Comment by rsto** [comment]
Fixed in 1a993b15ba5fd313332f7187ececa7e50b589bc1

In addition, we also decode MIME headers now properly, including RFC 2231 extended parameter using a new parser for extended mime header values (98f013ee74d023e3d72616fbc07428416b19e367).

For example, this attachment name

    Content-Disposition: attachment;
      filename*0*=utf-8''%F0%9F%98%80;
      filename*1=".txt"

now properly decodes to the attachment name

    😀.txt

**Comment by rsto** [comment]
d48c72d587eeeed5d3a7a2b1729d5054d42a791f and f04cc935a637ea69b5271f9d875201e2fc88c7b9 now to do the same for setMessages

However, there's still room for improvement in setMessages:


* handling very long file names that include non-ASCII (need to break in MIME parameter value continuations)
* rewriting the Content-Type "name" property (in QP-encoding, if necessary)

**Comment by rsto** [comment]
Fixed in 18e4d6be9d91e9f222588432de94ec926eeb83a6 and 898c35865ab4f010e91e071f6d26021165202bae
