### ISSUE TITLE
Implement missing 'onlyCountsChanged' property and verify mailbox state changes

### ISSUE THREAD

**Issue by rsto** [cyrusimap/cyrus-imapd#1997]
The `onlyCountsChanged` property is missing in the `getMailboxUpdates` implementation. Also, it has been reported that mailbox message count changes (e.g. number of unread messages changes), doesn't trigger a new mailbox state.

**Comment by rsto** [comment]
Cyrus currently tracks `mailfoldermodseq` for mailbox states, but these don't bump for message changes. We could use `mailmodseq` but would then also report mailbox updates for flagged messages.

The spec isn't totally clear what accounts to a mailbox state update, but the `onlyCountsChanged` property suggests that it at least must change for message counts.

**Comment by iNPUTmice** [comment]
Receiving efficient updates for read count changes is very important as future client will probably display that information in the sidebar.

>but would then also report mailbox updates for flagged messages.

I'd rather have a few unnecessary updates then no updates at all. Especially since a call to getMailboxUpdates with fetchProperties set to null and onlyCountsChanged set to true is pretty efficient in that case anyway. (Traffic wise. Not necessarily server load wise)

**Comment by iNPUTmice** [comment]
Hi. Thank you for working on this. With latest commit the state is updated but the `changed` array is still empty. To be fair you haven't closed this issue yet so you are probably aware of this.

**Comment by rsto** [comment]
Yes, I know. It's a bit tricky, we'll need to inspect the status cache for highestmodseq rather than mbentry's folder modseq.

**Comment by rsto** [comment]
Fixed in 39abcbb5e5a83fabcbc1604f0babf72646a08e57 and 73963aab5bf6f6546abd0b14fae9d6ac33ba51ed

Tested in https://github.com/cyrusimap/cassandane/commit/a3ed295d180de1ef54fea16c3170fadb40ffbbd1 and https://github.com/cyrusimap/cassandane/commit/9d9ba0e1471fa58394e8aeca535c6deb2ff816b2
