### ISSUE TITLE
JMAP: either standardise or vendor current x-properties

### ISSUE THREAD

**Issue by rsto** [cyrusimap/cyrus-imapd#1999]
### What's broken
The current Cyrus JMAP implementation uses a few x-properties:
    
    x-href (calendars, contacts)
    x-hasPhoto (contacts)
    x-importance (contacts)

The JMAP spec requires extension properties only to be exposed after client opt-in. Cyrus currently doesn't comply with the spec in this regard.

Also, the current JSEvent spec draft for calendar events requires custom properties to be vendored, e.g. `cyrusimap.org/href`, which contradicts the "x-" naming scheme.

### How to fix it
The current "x-properties" should be hidden until client opt-in and vendored or standardised. The properties in this issue look general enough to become part of the standard:

A `x-href` for CalendarEvent could be expressed as a `link` containing the URL of the iCalendar file and a `type` with value `text/calendar; component=VEVENT`. However, there is no `url` property defined for contacts.

Alternatively, both contacts and calendar events may get a `source` URI property to express a `x-href`.

In addition, a JMAP Contact could get both an `importance` and `hasPhoto` property.

**Comment by rsto** [comment]
@robmueller This might now be the perfect time to address how to handle these properties. For FastMail, I guess we'll use a couple of special JMAP `capabilities` in the request? Still, we'd need to vendor these x-properties to the fastmail.com/ prefix then.

**Comment by robmueller** [comment]
Part of the issue here is that the JMAP contacts and calendar spec hasn't had any discussion at the ietf at all yet, it's just what @neilj put together based on the FM requirements. It's likely to go through quite a few changes over time when it's finally submitted to the IETF. So basically, ALL of contacts and calendars is FM only right now, so I think for now, we'll probably have to use a fastmail:contact and fastmail:calendar capabilities to expose what we want for now, and deal with the changes that happen after the IETF process and creates ietf:contact and ietf:calendar. @neilj?

**Comment by neilj** [comment]
Yes. Although we should probably be using a domain we own for our own namespace. Ideally it will link to our docs e.g. `https://dev.fastmail.com/contacts` or `fastmail.io/contacts` etc. We should drop the `x-` prefix from everything too; that was only needed before we decided it should be opt-in.

**Comment by rsto** [comment]
We fixed that with capabilities and extension properties.
