### ISSUE TITLE
get rid of SMakefile

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#2069]
It must be super out of date by now, does anyone still use it for anything?

**Comment by rsto** [comment]
@elliefm just got this diceroll assigned. can look into this, or did you plan to work on it?

**Comment by elliefm** [comment]
Nah I just threw it out into the ether so it wouldn't get forgotten about, I don't know anything in particular or have any thoughts about it that's not in the original post :)

**Comment by jasontibbitts** [comment]
To be honest I can't understand why that file should stay.  The stuff in there is comically outdated, and the only thing that calls it is the "dist-old" makefile target (which obviously should just go as well).   All it did was run autoreconf and export some environment variables anyway.

The only other place it appears in the source is in contrib/drac_auth.patch which includes some rather old build instructions.  I have no idea if that patch is even relevant these days; it provides some type of pop-before-smtp thing which feels pretty 90s.  It certainly doesn't apply cleanly.

**Comment by rsto** [comment]
I agree with @jasontibbitts. I removed SMakefile and the dist-old target from master. I spent some time attempting to make the DRAC patch work with the current codebase, but it doesn't seem to be worth the effort. We can still revert the commit is someone is motivated to make it work with the current source.

Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/20961e4590a291a95fbca8fe4fb1151326844422
