### ISSUE TITLE
cyr_dbtool returns no records for users with '-' symbol

### ISSUE THREAD

**Issue by slimlv** [cyrusimap/cyrus-imapd#2073]
cyr_dbtool returns no record for user with '-' symbol:
    # cyr_dbtool /var/imap/mailboxes.db twoskip show user.alvi-l  
    # 
    # cyr_dbtool /var/imap/mailboxes.db twoskip show user.alvi | grep alvi-l
    user.alvi-l     %(A %(alvi-l lrswipkxtecda) P default M 1500985738)
    #
cyrus 2.5.11
improved_mboxlist_sort: 1

**Comment by elliefm** [comment]
cyr_dbtool's "show" action is just a cyrusdb_foreach with the given prefix, I can't see anything to be tripped over here?  I haven't been able to reproduce this on (approximately) current master yet so maybe it's already been fixed; I don't have a 2.5 install hanging around at the moment.

I have a vague memory that something about the sort order of "-" may have been broken/fixed at some point -- @brong, any recollection here?

**Comment by slimlv** [comment]
there is simple test case you can try to reproduce the issue: #2180

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
