### ISSUE TITLE
Makefile.am: install lib/util.h

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2079]
... as it is needed by lib/strarray.h and the latter is installed on "make install".

**Comment by elliefm** [comment]
At a first look, strarray.h only needs util.h for the compar_t typedef -- which is already duplicated by __compar_fn_t (also in util.h!) anyway.

So rather than installing another file (especially one which brings a lot of baggage), I'll see if I can clean up the strarray.h and arrayu64.h to not depend on it anymore.

**Comment by elliefm** [comment]
This is great, it's turning up a bunch of mess in our include structure...

**Comment by elliefm** [comment]
Though all that said, util.c is included in libcyrus_min so its header probably needs to be installed anyway

**Comment by elliefm** [comment]
strarray.h should no longer depend on util.h on master and cyrus-imapd-3.0 branches as of last couple of commits to each.  Likewise arrayu64.h
