### ISSUE TITLE
[2.5.11] squatter -r fails recursing over #addressbooks and #calendars

### ISSUE THREAD

**Issue by MASHtm** [cyrusimap/cyrus-imapd#2185]
If a mailbox has a global "squat: true" setting which is inherited by all children squatter -r fails reaching 'user.\<uid\>.#addressbooks*' or 'user.\<uid\>.#calendars*' because index_open() returns IMAP_MAILBOX_BADTYPE and squatter quits immediately after getting this error.

A workarround is to set "squat: false" on these mailboxes, but this is pretty difficult since they are autogenerated on first access.

I think this fixes it correctly:
```
--- a/imap/squatter.c   2017-05-09 02:40:13.000000000 +0200
+++ b/imap/squatter.c   2017-10-27 15:07:18.228433175 +0200
@@ -552,7 +552,8 @@

         return 1;
     }
-    if (mbentry->mbtype & MBTYPE_REMOTE) {
+    if ((mbentry->mbtype & MBTYPE_REMOTE) ||
+        (mbentry->mbtype & MBTYPES_NONIMAP )) {
        mboxlist_entry_free(&mbentry);
        return 0;
     }
```

Works fine here.

**Comment by elliefm** [comment]
I've merged this into 2.5, thanks!

I'm not sure if this is needed on 3.0/master -- `index_open_mailbox()` on these versions has some handling to support opening non-imap mailboxes under certain circumstances (with imapmagicplus stuff), so I'm not sure if it's right for squatter to just ignore them, or to try to factor that in.

**Comment by elliefm** [comment]
@rsto @ksmurchison I'd appreciate any input either of you might have to offer here, regarding squatter indexing of #addressbooks/#calendars.  Does anything need to be done for the 3.0 and master branches?

**Comment by rsto** [comment]
In version 3, we index selected text fields from iCalendar messages in #calendars. E.g. here is the code in [index.c](https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/index.c#L4961).

I haven't tested what happens if HTTP support isn't enabled, though.

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
