### ISSUE TITLE
When tls_sessions.db is missing, Cyrus IMAP does not start

### ISSUE THREAD

**Issue by dmak** [cyrusimap/cyrus-imapd#2207]
The expected behaviour (perhaps for most `/var/lib/cyrus/*.db`) is to create this database if it is missing. However when e.g. `tls_sessions.db` is missing, Cyrus fails to start:

    cyrus/tls_prune[8432]: DBERROR: opening /var/lib/cyrus/tls_sessions.db: cyrusdb error
    cyrus/master[8411]: process type:START name:tlsprune path:/usr/sbin/cyrus age:0.000s pid:8432 exited, status 1
    cyrus/master[8411]: can't run startup
    cyrus/master[8411]: exiting

Cyrus IMAP v2.5.10-3

**Comment by elliefm** [comment]
I think (vague memory) this might have been fixed more generally in 3.0, but I'm not sure.  Will look into it, and backport if appropriate.

In the meantime, here's a 2.5-specific patch that I haven't tried forward porting yet.  It just accepts tls_sessions.db as "nothing to do" for the purposes of pruning, rather than as a serious error:  https://github.com/elliefm/cyrus-imapd/commit/1e7cf05a6bcba8c639fe8222c28851b1a9802e63

Does that get you going?

**Comment by dmak** [comment]
Thanks for looking into that. The patch overall looks fine, few remarks / questions:
- I actually could not find the code that creates this database. If this code is there, then it should be invoked before `tls_prune_sessions()` so that database is guaranteed to be created.
- Can the same strategy be applied for other databases (e.g. `user_deny.db`, `statuscache.db`)?
- Not all execution branches in function `tls_prune_sessions()` free the memory, e.g. `free(tofree)` is called only when `ret == CYRUSDB_OK`.

**Comment by elliefm** [comment]
Yeah, I saw those memory leaks, but didn't want to clutter a bunch of unrelated fixes into the patch.  I'll tidy those up separately.  Thanks though :)

The creation of the database file is handled by passing the CYRUSDB_CREATE flag (or something like that -- it's in lib/cyrusdb.h, which I'm not presently looking at) to the `flags` argument of `cyrusdb_open()`.  The `tls_prune` tool just passes 0 here -- which makes sense, cause if there's no database there's nothing to prune.  I've chosen to keep this behaviour for tls_prune specifically.

I believe -- but haven't verified -- that the database should be automatically created when a session is written down to it (because that part of the code does use the create flag).  At least, we haven't had reports of database errors at that point.

In my opinion, this approach should be generally correct for all databases: things that need it to exist should open it with the create flag; and things for which no database == no work to do should gracefully handle it not existing.  I believe this is pretty consistent in 3.0 but I'm not sure what state 2.5 is in.  If you find more bugs like this I'm happy to fix them up, and would welcome patches along these lines, but I doubt I'll spend any time on a general audit.

**Comment by elliefm** [comment]
`tls_prune` is now fixed on 2.5, 3.0 and master branches.  Thanks for the report :)

**Comment by daramousk** [comment]
Not sure if I am reporting this at the right place but for some reason I had the same issue with version 2.5.10-3 on debian (reported it at Debian as well)

> Dec 31 21:19:28 bit cyrus/tls_prune[21430]: DBERROR: opening /var/lib/cyrus/tls_sessio
ns.db: cyrusdb error                                                                      
Dec 31 21:19:28 bit cyrus/master[21423]: process type:START name:tlsprune path:/usr/sb
in/cyrus age:0.000s pid:21430 exited, status 1                                            
Dec 31 21:19:28 bit cyrus/master[21423]: can't run startup   

After `touch` and `chown`ing the file everything seems to be working correctly. The file seems to not be created upon installation of the package.
