### ISSUE TITLE
experimental LMDB support -- remove from 3.0?

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#2238]
There's experimental support for [LMDB](https://symas.com/lmdb/) as a database format in 3.0.  It's been removed from master because it was found to be unsuitable, but I don't remember the specifics.

Need to consider whether to let this stagnate on the 3.0 branch, or pull it out.  I don't think it's a burning issue either way.  Probably worth a look and see how intrusive it would be to pull out.

**Comment by postilion** [comment]
I remember @brong being quite exercised about this at the time, but then haven't heard any more since.  It's a rather compact format, and seems to serve the OpenLDAP folks well, but then...zeroskip?
-nic

**Comment by elliefm** [comment]
d1ff37f37 is where it was ripped out of master, for whatever that's worth.  Looks pretty low-impact.

**Comment by rsto** [comment]
> @brong, @rsto, do either of you recall more details on why lmdb didn't work out for us?

What brong said. The corruption issue most probably was because of my glue code to hook LMDB into our DB API, but we never managed to reproduce the steps leading to the corrupt databases.

Plus: As quite a bunch of similar DBs, LMDB is quite greedy in not giving up allocated disk space. They just kept growing and growing until we manually compacted. That's a design choice of LMDB for good reasons, but didn't fit into our usage case of having one LMDB per user.

**Comment by elliefm** [comment]
I think I've decided that I'm going to leave it in 3.0, and if people want to experiment further with it and maybe come up with a fix, then we can consider bringing it back on master in the future.

It's not hurting anything by hanging around (unlike the out-of-date JMAP)
