### ISSUE TITLE
setMailboxes/create does not prevent mailboxes with same name

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2275]
The spec (https://github.com/jmapio/jmap/blob/master/spec/mail/mailbox.mdown#mailboxes) says:

````
name: String User-visible name for the mailbox, e.g. "Inbox". This may be any Net-Unicode string ([@!RFC5198]) of at least 1 character in length and maximum 256 bytes in size. Servers SHOULD forbid sibling Mailboxes with the same name. Servers MAY reject names that violate server policy (e.g., names containing slash (/) or control characters).
````

We don't seem to enforce this, but the spec only says `SHOULD` so maybe that's okay? But how will this look to imap clients if I have 5 folders with the name "foo"?

**Comment by rsto** [comment]
Long time ago, the spec recommended to allow siblings with same names, and this is what's still implemented in Cyrus. For IMAP, we resolve same-name siblings by finding unique names for the mailbox. E.g. if you create three mailboxes named "foo" under the same parent, you'll currently get in IMAP:

- `INBOX.foo`
- `INBOX.foo_1`
- `INBOX.foo_2`

Couple of weeks ago I realised the spec now recommends to forbid same-name mailboxes, and there's consensus to drop support for it also in Cyrus. So that's what I'll do.

**Caveat:** dropping same-name support has an unwanted side-effects: The Cyrus server does not implement invalid interim states in `set` operations, so a client has to come up with a sequence of renames if it would like to swap names of two siblings mailboxes.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/b4e1f7d202a3e609f65e645174062d3467d07a78

Caveats apply
