### ISSUE TITLE
EmailSubmission/set returns strange state string (not modseq)

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2297]
When sending an email, the UI makes this set of API calls:

```
0 | Email/set
1 | {…}
  accountId | u15894385
  create | {…}
    k42 | {…}
      attachments | null
      bcc | null
      cc | null
      from | {…}
      headers | {}
      identityId | 51361153
      keywords | {…}
        $draft | true
        $seen | true
      mailboxIds | {…}
      receivedAt | 2018-03-19T00:40:44Z
      subject | asdgasdg
      textBody | asdgadsgasgd  --    robm store254   robm_test@fastmail.fm
      to | {…}
2 | 0

0 | EmailSubmission/set
1 | {…}
  accountId | u15894385
  create | {…}
    k43 | {…}
      emailId | #k42
      envelope | null
      identityId | 51361153
      onSuccessUpdateEmail | {…}
        #k43 | {…}
          keywords/$draft | null
          mailboxIds/83633ba7-f347-44b1-8742-473474f9787e | null
          mailboxIds/cea2e21c-d44e-4bd2-b07a-6bd4b887c33a | true
2 | 1
```

```
0 | Email/set
1 | {…}
  accountId | u15894385
  newState | 270
  oldState | 270
  created | {…}
    k42 | {…}
      id | M77f33630e7b3ef99bcb11971
2 | 0

0 | EmailSubmission/set
1 | {…}
  accountId | u15894385
  newState | cb3c7b46-ae9c-413e-a033-c21df87f2f8c
  oldState | 273
    created | {…}
      k43 | {…}
        id | a6b87396-4165-448b-90d0-0c486d459060
2 | 1
...
```

That "newState: cb3c7b46-ae9c-413e-a033-c21df87f2f8c" doesn't look right at all, it's using some internal UUID rather than a mailbox modseq. This might confuse the UI significantly.

**Comment by rsto** [comment]
That's on purpose.

The current EmailSubmission implementation Cyrus is trivial: All it does is to support create, and whenever that succeeds it creates a random new state. We can't use the account's modseq counters, because we'd violate the requirement that the EmailSubmission state changes for every change. If two EmailSubmission/create succeed without a message being updated or created in between, we'd return the same state string for two different EmailSubmission states.

In terms of the spec, the UI shouldn't bother at all what the state string looks like. It's an opaque thingie that the server is allowed to change anytime.

If we want to make that a special value, we can do so, of course.

**Comment by robmueller** [comment]
Are EmailSubmission objects stored anywhere? Can you /get them or /changes on them?

**Comment by rsto** [comment]
No, in the current implementation you can't. That's why we just use this random state string. Once /get et all are supported on EmailSubmission the state has to change to a more meaningful value, of course.

**Comment by robmueller** [comment]
Right got it, no problem then :)
