### ISSUE TITLE
JMAP: attachments added to emails are includes raw as is, not encoded

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2364]
When an attachment is added via Email/set and then the message sent via a EmailSubmission, the attachment content is included raw as is. This can result in binary 8bit data (including \0 chars) in the generated email. It should be appropriately encoded (e.g. base64 or quoted-printable if necessary).

There's lots of possible options here to try and represent the data "nicely" (e.g. a text/* mimetype attachment with ascii only text data with short lines is included as 7bit, binary data is base64 encoded, mostly ascii with small numbers of high-bit chars is quoted-printable encoded, etc), but maybe as a first pass we should just base64 encode everything. This avoids needing to inspect the content for now, but maybe do things in a way so that in the future we can try and be a bit more "nice" about which encoding type to use based on mime type + content inspection?

**Comment by rsto** [comment]
Weird, I could have sworn this is already done, but I don't see the code doing this. Of course, this is bogus.

**Comment by rsto** [comment]
I've pushed https://github.com/cyrusimap/cyrus-imapd/commit/3377fb3b8fa5c7f4d2128b4311c2f4a48e3b42c8

which applies the following logic:
- If the blob is top-level Cyrus message, it already is a properly encoded message/rfc822 MIME part, and no encoding is required
- if the blob already defines a Content-Transfer-Encoding header, use that one and use the verbatim encoded data
- if the JMAP clients defines this attachment to be of type 'message' (e.g. 'message/rfc822'), do not encode the body (e.g. the client uses a blob of another JMAP Email, otherwise it should know what it's doing).
- otherwise, base64-encode the blob

Note that for encoding of text bodies (not as attachment), we already apply QP-encoding, if required.

**Comment by robmueller** [comment]
That logic sounds like a good start. Nice.
