### ISSUE TITLE
JSCalendar event: duration returns 'W', but weeks are not allowed in spec

### ISSUE THREAD

**Issue by rsto** [cyrusimap/cyrus-imapd#2381]
The duration property is returning "W" (week) components for events, but the JSCalendar spec says only D, H, M and S are allowed.
(created new issue from: https://github.com/cyrusimap/cyrus-imapd/issues/2380)

**Comment by rsto** [comment]
@neilj I wonder why we chose to not allow weeks in JSCalendar durations? Is there a reason that I have missed in the design discussions?

**Comment by neilj** [comment]
I believe it was because ideally we want a canonical format for any duration, so you can see if two events have the same duration by just comparing the strings, rather than having to parse them. However, at the moment we don't have enough restrictions in JSCalendar for this to be the case (e.g. `PT3M`, `PT0H3M` and `PT3M0S` are all currently valid values for 3 minutes, so I guess we either add further restrictions or we might as well allow weeks.

**Comment by rsto** [comment]
Obsolete. [jscalendar-05](https://tools.ietf.org/html/draft-ietf-calext-jscalendar-05) allows durations to have week parts.
