### ISSUE TITLE
specialusealways: 0? /  SPECIAL-USE with simple LIST

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2410]
[RFC 6415](https://tools.ietf.org/html/rfc6154) says: Section 5.1 Example of an IMAP LIST Command

> C: t1 LIST "" "%"
> S: * LIST (\Sent \HasNoChildren) "/" SentMail

Section 5.2 Example of an Extended IMAP LIST Command
> C: t2 LIST "" "%" RETURN (SPECIAL-USE)
> S: * LIST (\Sent) "/" SentMail

Note how \Sent is returned also in the non-extended LIST.  Cyrus 3.0 does:
> C: t1 LIST "" "%"
> S: * LIST (\HasNoChildren) "/" Sent
> S: * LIST (\HasNoChildren) "/" Spam

But
> C: t1 LIST "" "%" RETURN (SPECIAL-USE)
> S: * LIST (\HasNoChildren \Sent) "/" Sent
> S: * LIST (\HasNoChildren \Junk) "/" Spam

Cyrus IMAPD 3.0 should have returned \Sent and \Junk in the non-extended LIST.  Gnome Evolution is supposed to understand SPECIAL-USE, but does not with Cyrus by default, so probably it relies on the simple LIST.

Why is `specialusealways` by default `off` and hence by default does not implement the RFC correctly?

**Comment by brong** [comment]
On Tue, Jun 26, 2018, at 08:14, Дилян Палаузов wrote:
> RFC 6415[1] says: Section 5.1 Example of an IMAP LIST Command



I assume you mean 6154.

>> C: t1 LIST "" "%"
>>  S: * LIST (\Sent \HasNoChildren) "/" SentMail


> Section 5.2 5.2.  Example of an Extended IMAP LIST Command


>> C: t2 LIST "" "%" RETURN (SPECIAL-USE)
>>  S: * LIST (\Sent) "/" SentMail


> Note how \Sent is returned also in the non-extended LIST.  



Yes, though that is optional.  The examples in the RFC show a server
which returns the special-use information without the RETURN option
being specified, but they don't require it.
> 
> Cyrus 3.0 does:
>> C: t1 LIST "" "%"
>>  S: * LIST (\HasNoChildren) "/" Sent
>>  S: * LIST (\HasNoChildren) "/" Spam


> But


>> C: t1 LIST "" "%" RETURN (SPECIAL-USE)


>>  * LIST (\HasNoChildren \Sent) "/" Sent
>>  * LIST (\HasNoChildren \Junk) "/" Spam> Cyrus IMAPD 3.0 should have returned \Send and \Junk in the non-
> extended LIST.  Gnome Evolution is supposed to understand SPECIAL-USE,
> but does not with Cyrus, so probably it relies on the simple LIST.

Which is why we have an option:

{ "specialusealways", 1, SWITCH }
/* If enabled, this option causes LIST and LSUB output to always include   the XLIST "special-use" flags */

Which defaults to on in 3.1, but off in 3.0.  So if you want it in 3.0,
add "specialusealways: yes" to your imapd.conf.  It defaulted to "off"
in 3.0 because there was some concern that it would confused clients
which didn't understand specialuse - but sufficient real-world testing
suggested it wasn't a problem, hence the changed default in 3.1.
Cheers,

Bron.


--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com



Links:

  1. https://tools.ietf.org/html/rfc6154

**Comment by dilyanpalauzov** [comment]
Please update the documentation on this for maser:
```diff
diff --git a/docsrc/imap/rfc-support.rst b/docsrc/imap/rfc-support.rst
--- a/docsrc/imap/rfc-support.rst
+++ b/docsrc/imap/rfc-support.rst
@@ -559,6 +559,11 @@ The following is an inventory of RFCs supported by Cyrus IMAP.
 
     IMAP LIST Extension for Special-Use Mailboxes
 
+    .. NOTE::
+
+        The LIST and LSUB commands return the special-use flags, unless the
+       ``specialusealways`` configuration variable is explicitly turned off.
+
 :rfc:`6321`
 
     xCal: The XML Format for iCalendar
```
and cyrus-imap-3.0:
```diff
diff --git a/docsrc/imap/rfc-support.rst b/docsrc/imap/rfc-support.rst
--- a/docsrc/imap/rfc-support.rst
+++ b/docsrc/imap/rfc-support.rst
@@ -545,6 +545,11 @@ The following is an inventory of RFCs supported by Cyrus IMAP.
 
     IMAP LIST Extension for Special-Use Mailboxes
 
+    .. NOTE::
+
+        The LIST and LSUB commands don't return by default the special-use flags,
+        unless ``specialusealways`` is turned explicitly on.
+
 :rfc:`6321`
 
     xCal: The XML Format for iCalendar
```

**Comment by dilyanpalauzov** [comment]
Documentation is now updated accordingly.
