### ISSUE TITLE
JMAP: Implement Quota extension

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2559]
FastMail is currently using a JMAP extension to do quota reporting to the UI. Currently this is done in the perl middleware but it's annoying because:

1. We have to maintain an IMAP connection to get quota details. I really want to avoid maintaining an IMAP connection for JMAP users
2. The middleware currently isn't doing a great job of sending quota updates back to the client. It could be made better, but basically it would have to intercept Email/set actions and make IMAP calls again.

Given cyrus already knows what causes quota changes, it would be great to push this work down to cyrus.

This is the current Quota object spec.
```
A **Quota** object has the following properties:

- **used**: `Number`
  Storage used in MB, rounded to the nearest MB
- **total**: `Number`
  Total storage available in MB, rounded to the nearest MB

## Quota/get

Standard */get* method. The *ids* argument may be `null` to fetch all at once.

Objects with the following ids exist in FastMail:

-`mail`: Mailbox quota (used for mail, calendars and contacts)
-`files`: Files quota (ignore this one, we do this in the middleware)

**Note**: The server may at any time add an unrequested *Quota/get* response
to the list of responses it sends to the client, if it thinks the usage may have changed.
```
So what should be implemented in cyrus:
1. The Quota/get method that supports ids => null or ids => [ "mail" ]
2. Whenever a JMAP action changes the used quota, an unsolicited `Quota/get` response is added to the `methodResponses` list. If multiple methods change the quota, then only a single `Quota/get` response should be added at the end after all the methods are completed.
3. I don't think there's a modseq associated with the quota, but it would be good to get quota updates if any other connection (IMAP or delivery or other JMAP process) makes a change. I think the easiest way of doing this is an `Email/changes` call is made, return an unsolicited `Quota/get` response as well if there's *any* changes since the given state string

All of this should probably be activated by a using extension "http://cyrusimap.org/ns/quota"

**Comment by brong** [comment]
Here's what I think we need to do in terms of data structure changes:

1) add a QuotaModseq field to the counters:  https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/mboxname.c#L2082 and onwards - add a new version with the additional data field, etc.  It may be worth a new entry point as well since this one isn't a "mbtype" as such.

2) add Modseq to the quota data format: https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/quota_db.c#L154 (optional: convert to using dlist_sax parsing)

3) update quota_write https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/quota_db.c#L411 to set the modseq every time the quota usage (or limit) changes AND the quotaroot is for a user-owner mailbox.

4) make sure mboxevent counters field includes the quota limit as well so we can push changes based on it.

5) profit.

Oh yeah, we'll need to implement Quota/get at least, and maybe Quota/set.  There's multiple types of quota in that file, but Storage is the key one.

3) update the pusher code to read the new version of the counters and push a Quota type modseq.

**Comment by rsto** [comment]
Implemented in https://github.com/cyrusimap/cyrus-imapd/commit/d5ecb3decbaed8ebc6c330e1e76e0854beb93860
