### ISSUE TITLE
--with-cyrus-group configure option currently unused

### ISSUE THREAD

**Issue by J5lx** [cyrusimap/cyrus-imapd#2639]
I would like to use systemd-sysusers to create the cyrus user, however that tool currently assigns each system user a primary group of the same name, while I’d like Cyrus to use the mail group. At first I thought this wasn’t a problem because I had seen there was a configure option for the group used by Cyrus which defaults to mail, but then I noticed that Cyrus ignores this option and always uses the primary group of its user.

Could you change the behaviour to handle the group in the same way as the user (i. e. env var → config var → configure-time default) or would you accept a PR for that?

Also, this change would require those who previously used a primary group other than mail without setting the configure option to update their setups. Is this a reasonably unlikely scenario that it can be ignored (since the documentation always assumes cyrus:mail) or would it be better to figure out a way to not affect those systems?

**Comment by elliefm** [comment]
I'm not sure what it would even look like for Cyrus to override the primary group of its user?  I guess a conditional `setgid()` call in every single binary?  (That smells like a headache.)  At the moment, everything it does, it just does as the uid/gid that it's running as, like anything else. 

Digging through the history, it looks like the `--with-cyrus-group` option was added (in 1996) for the specific purpose of setting the group ownership when installing the `deliver` binary -- it doesn't seem to have ever been used for anything else.  It looks like this detail was lost (in 2012) when the project switched to using automake instead of a hand-maintained Makefile.in, but the obsolete option wasn't removed.  Anyway, seems like it's been a very long time since this option did anything!

I tend to think it's better for Cyrus to continue doing the normal thing (i.e. just using whatever the system gives it), and if you want to do something with your user/group, configure it in the system level, not in Cyrus.  I could be convinced otherwise, but at the moment my inclination is to remove the obsolete option, rather than try and resurrect it.

I'm happy to review a proof of concept? I'm curious to see how you envision this working, at least

**Comment by J5lx** [comment]
Actually, what I was thinking about is the setgid call that’s already present in lib/util.c in become_cyrus. The supplied gid is currently hardcoded as the primary gid of the cyrus user, I’d just like that to be explicitly configurable like the user. I think I could have worded my original post more clearly there. I’ll be happy to get a proof of concept ready.

I’m not quite sure I get what you mean by using what the system gives Cyrus – do you mean setting the cyrus user/group through the init script/systemd unit? It doesn’t seem to be documented anywhere though, and earlier when I looked at various distribution packages for orientation (Debian, Fedora, openSUSE), I didn’t see that approach anywhere (unless I overlooked something). However, you’re talking about „the normal thing”, so could it be that I’m just misinterpreting you?

**Comment by J5lx** [comment]
Proof of concept is at #2642.

**Comment by elliefm** [comment]
Ah, I see what you mean.  Yeah that's very neat and tidy, thanks!

> I’m not quite sure I get what you mean by using what the system gives Cyrus

> The supplied gid is currently hardcoded as the primary gid of the cyrus user

Pretty much just that, heh :)

**Comment by elliefm** [comment]
Whoops, merged that a bit fast -- have just tested it and the default behaviour is now quite different.  Have reverted it, though github doesn't seem to recognise the revert and attach it to the PR, so the PR still looks "merged".

I think what we want here is for the default to remain "the cyrus_user's primary group", rather than "mail"?  Which I think we would do by allowing `cyrus_group()` to return NULL if it didn't find an override to use, and then `become_cyrus()` would only do the `getgrnam()` call if it found a group name to look up, otherwise it'd just use the `p->pw_gid` field like it used to

**Comment by J5lx** [comment]
Yeah, that’s basically what I was talking about in the last paragraph of the OP. I did it like this because it’s the behaviour I’d personally expect when ignoring the compatibility issue, but forgot to mention it in the PR. Sorry about that! If I understand your suggestion correctly, I’ll just remove the configure option altogether then (since it wasn’t being used before and the removal only results in a warning if it gets used anyway) and only use the env var and the config option (in a new PR).

One more thing, once the solution is good, would it be possible for it to go into 3.0 as well? (It should apply cleanly)

**Comment by elliefm** [comment]
I've just done an eyeball review and that's looking good so far, will pull down the branch and test it shortly.

I'm pretty happy with this version going to 3.0: it doesn't remove or change any existing functionality, the new behaviour is optional and not enabled by default, and the code change is unintrusive :)

**Comment by elliefm** [comment]
Well, it doesn't break my test environment anymore! :)

I'm wondering if it's worth mentioning that the user that starts the master process will need permission to become the specified group, or if we can assume someone overriding the cyrus_user/cyrus_group defaults already knows that.  It's not our job to document unix user/group management, but maybe it's worth at least prompting that it's a factor... what do you think?  Probably just a sentence in imapoptions, if anything, I guess.

**Comment by elliefm** [comment]
I guess we haven't bothered to say anything for cyrus_user, so we should either do it for both or continue to not bother.  I don't actually have a strong opinion either way!

**Comment by J5lx** [comment]
Personally, I don’t feel like talking about that in the documentation – properly setting up a mail server requires a certain amount of know-how to begin with, so I’d say that those people who need to change this option probably don’t need that sort of documentation.

**Comment by elliefm** [comment]
Cool, sounds good to me :)  Merged, and will backport to 3.0 shortly

**Comment by elliefm** [comment]
Cherry-picked cleanly, will be in next 3.0 release. Thanks very much for your work on this! :)

**Comment by J5lx** [comment]
Thank you for taking the time to discuss and review this!
