### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cyrusimap/cyrus-imapd#2648]
[An extra null pointer check is not needed in functions](http://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [free_message_list](https://github.com/cyrusimap/cyrus-imapd/blob/bb88f7f37e5fd3c3f3cf4fbd488839dec232f678/imap/objectstore_db.c#L79)
- [mycanonifyid](https://github.com/cyrusimap/cyrus-imapd/blob/4b36ed8e35b84bb5e06d401851d9528ae9382926/lib/auth_krb5.c#L94)
- [varlist_fini](https://github.com/cyrusimap/cyrus-imapd/blob/bb88f7f37e5fd3c3f3cf4fbd488839dec232f678/sieve/varlist.c#L52)

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle") to find more update candidates?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by elliefm** [comment]
Nope. While these checks are not "needed" by the compiler, they are very useful to the human maintainers of the code: they provide a strong contextual hint that, in the preceding code, we expect the pointer may not have been allocated.

Thanks for checking though! :)

**Comment by elfring** [comment]
I suggest to reconsider the need for the mentioned kind of “contextual hint”.
Can a bit less source code result in a positive effect on software maintenance and run time behaviour?

**Comment by elliefm** [comment]
I mean, I've already stated that they are very useful. Let's assume that I'm speaking from experience and know what I'm talking about: there is a positive benefit to having these.

What aids software maintenance is reduced _complexity_, not reduced lines of code.  Removing these lines increases complexity: the maintainer, upon reviewing the code above, needs to decide if the pointer being sometimes initialised and sometimes not is a deliberate design choice or a bug.  The conditional free below provides the documentation: this is deliberate, we expect this; without it, one must look elsewhere to figure that out.  In a large, decades old software project where no one person knows every part of the codebase, that can often mean poring through commit history to decipher intent.

If there's a performance benefit to be had by removing these branches, the place to make that optimisation is in gcc/clang so that every project benefits.  It's an obvious enough target that I wouldn't be surprised if these aren't already optimised out by -O1.  I haven't analysed the generated machine code, but nor has anyone reported a performance bottleneck that traces back to these branches, so it's reasonable to suppose there's not much to gain.

From a user perspective, if you aren't already keeping your hot data on SSD and your temporary databases on tmpfs, a few extra short branches are the _least_ of your performance concerns.

**Comment by elfring** [comment]
>Removing these lines increases complexity:

I am following a way of thinking (which is also applied in other software areas) here that redundant case distinctions can result in undesirable effects.


>The conditional free below provides the documentation:

Should the system properties be better known for the affected function calls?


>… without it, one must look elsewhere to figure that out.

Is this eventually expected if you feel unsure about a standard programming interface?


>…, the place to make that optimisation is in gcc/clang so that every project benefits.

* Would you like to help with further evolution in this area?
* Can any software developers and system testers become occasionally more interested in another code size reduction?

**Comment by dilyanpalauzov** [comment]
```
// if (x):
   free(x)
```
is equally siuted to fulfilll the documentation purposes.
