### ISSUE TITLE
FTP server not reachable

### ISSUE THREAD

**Issue by Sauerbier** [cyrusimap/cyrus-imapd#2758]
Hey,
seems like ftp.cyrusimap.org is down.
I can't access it nor ping the server.
I hope it's not a major issue :)

Best regards,
Jan

**Comment by elliefm** [comment]
Thanks, it's known, and has been down for a while (like, since christmas).  At this point, it's probably a safe bet that it won't be back.

You can get source releases via HTTPS at https://www.cyrusimap.org/releases/ or https://github.com/cyrusimap/cyrus-imapd/releases

We're in the process of moving the cyrusimap.org domain off its old hosting at CMU, but it requires a bunch of coordinated work from a bunch of people that don't have that work in their job description, so it's slow going!
