### ISSUE TITLE
JMAP extension: Email/query fromContactGroupId filter condition

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2799]
Another custom filter condition to add:

- **fromContactGroupId**: `String`
  The id of a contact group in this account. The server should look up the email addresses for all contacts in the group, and do a query equivalent to `from:<address1> OR from:<address2> OR ... etc.`. The state string of the response should include the modseq from the contacts so it will change if the contact group changes.

We probably should add equivalent `toContactGroupId`, `ccContactGroupId`, `bccContactGroupId` if not too hard, but these are not essential.

**Comment by rsto** [comment]
I got an initial implementation, but there's a couple of points to consider:

- how should unknown groupIds be handled? I assume we reject the filter as invalid then, pointing in the error description to the offending group id(s)?
- I guess we need support for addressbookId? Should that be set on the Email/query request arguments?
- using this filter currently incurs the cost of looking up the group and member records, even if the search result is cached. that's because we use the Cyrus-internal representation of the search tree as cache key (and we can't generate that tree without knowing the email addresses). If the search is cached, it will still benefit from the cache by not looking up the Xapian backends.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/6877c6e974e7bc5ecea552888bd23dd89a8e950e
