### ISSUE TITLE
urlfetch: If you haven't selected a folder yet, we crash because we don't have an index yet

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2826]
See: https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/imapd.c#L13932 as below:

```
        if (!strcmp(index_mboxname(imapd_index), intname)) {
            state = imapd_index;
}
```

**Comment by elliefm** [comment]
`index_mboxname()` returns NULL if there's no mailbox currently selected, so the problem is we're using a bare `strcmp()` when one of the arguments might be null.  We should be using `strcmpsafe()` or `strcmpnull()` here... I think `strcmpnull()` is the more correct choice, because we don't want any tricksy empty-string stuff.

**Comment by elliefm** [comment]
I'd love a Cassandane test for this but I don't know URLFETCH syntax well enough to contrive one that I trust to prove that I didn't break anything...

The existing Fetch.fetch_urlfetch test doesn't appear to directly invoke the URLFETCH command, instead it does some kind of append and concatenates some message parts by url into a new message??  I'm sure it's a sensible test but it's not giving me a baseline to copy and paste a new test from 😂

**Comment by elliefm** [comment]
Anyway it doesn't seem to break any of our _existing_ tests so I've pushed that fix ^^
