### ISSUE TITLE
JMAP: Wrong header field is returned when :all is not used

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2862]
If you fetch a header field XXX and there are multiple header fields with this name, the *last* one should be returned, as per https://tools.ietf.org/html/rfc8621#section-4.1.3:

```
 o  :all

      This means the value is an array, with the items corresponding to
      each instance of the header field, in the order they appear in the
      message.  If this suffix is not used, the result is the value of
      the *last* instance of the header field (i.e., identical to the
      last item in the array if :all is used), or null if none.
```

Cyrus is currently returning the value of the *first* header field, which is wrong.

**Comment by rsto** [comment]
Is that issue showing up for a particular header? I just tested this for a MIME message with the following headers (in this order):

    X-Tra-Header: val1
    X-Tra-Header: val2

which returns for a `Email/get` request for property  `header:x-tra-header`

    "header:x-tra-header": " val2"

**Comment by neilj** [comment]
Yes, I'm doing "header:snoozed-original-date:asDate" and getting back the first, not the last.

**Comment by elliefm** [comment]
I've changed the implementation of this because it broke IMAP header search.  There's now a `MESSAGE_LAST` flag for `message_get_field()` (and without this flag it uses the old return-all-values behaviour), and `_email_get_header()` in jmap_mail.c passes this flag (916fc6c26 and 6ec6fce43).

I'm not sure if this is completely the right fix, but it passes the JMAPEmail.email_get_header_last_value test that @rsto added for this case, fixes IMAP header search, and doesn't break anything else (that we have a test for...)!

Looking really close, it looks like maybe the real bug was in `_header_as_date()`, which is given a raw string containing all the values for a header, and converts only the first one into a date.  But also looking real close, all the `_header_as_foo()` converters look like they expect only a single value.  So given that, making sure they only receive a single value (the last one) might be the right fix after all.
