### ISSUE TITLE
Conversation subject normalisation does not support non-ASCII languages

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2873]
We split conversations when the subject changes significantly. A significant change ignores the Re:/Fwd: etc. that is prepended to replies/forwards. However, the [current regex for stripping this](https://github.com/cyrusimap/cyrus-imapd/blob/322cb2e0c5b0bf3a2c487c06bf70763250710642/imap/conversations.c#L762) is:

    ^[ \t]*[A-Za-z0-9]+(\\[[0-9]+\\])?:

I believe we should change this to:

    ^[ \t]*[^\s]+:

Basically strip any "word" that ends with a colon at the beginning of the string. This will fix, for example, Chinese "Re:" which is "回复:".

We can make this change without rebuilding everyone's conversations DB, as it should be mostly backwards compatible. However, it may cause a few conversations to be split that shouldn't be I guess if they happen to have subjects that would normalise differently under this new scheme, so we should consider the best rollout plan with care.

**Comment by elliefm** [comment]
The comment above that function says (in part):

>  *  - We eliminate leading tokens like Re: and Fwd: using a simpler
>  *    and more generic rule than RFC5256's; this rule catches a number
>  *    of semantically identical prefixes in other human languages, but
>  *    unfortunately also catches lots of other things.  We think we can
>  *    get away with this because the normalised subject is never directly
>  *    seen by human eyes, so some information loss is acceptable as long
>  *    as the subjects in different messages match correctly.

I wonder if RFC5256's version of this rule would do what we want here?  If it would do what we want, it seems like it might be preferable to use it, rather than continuing to tweak a "simpler, more generic, but unfortunately..." bespoke one?  Looks like the algorithm is described at [2.1](https://tools.ietf.org/html/rfc5256#section-2.1) and the ABNF at [5](https://tools.ietf.org/html/rfc5256#section-5).

**Comment by neilj** [comment]
No, this would be way worse than now, because this RFC completely fails to account for people using localised forms of Re/Fwd and so will break conversations in these cases.
