### ISSUE TITLE
master: exit with error if ports cannot be bound

### ISSUE THREAD

**Issue by robn** [cyrusimap/cyrus-imapd#2902]
If master cannot bind a port during startup, it will log:

```
2019-10-28T18:48:28.930907-04:00 imap2 sloti2d3t17/master[3095803]: unable to bind to httpd/ipv4 socket: Address already in use
```

and then continue with that port unbound. That can give the appearance the Cyrus is "up", but certain services may not be available.

Better would be to just exit with error if any port can't be bound, so we can always be sure that either all services are available or none of them are.

**Comment by elliefm** [comment]
It does this inside a loop over the `getaddrinfo()` results, and when it hits this condition it `continue`s with the next result, I guess supposing that one of the other results might be appropriate.

If, after everything, it hasn't got any proper socket for the service, it'll disable it (but in such a way that it'll try to start it up again on SIGHUP):

```
    if (nsocket <= 0) {
        syslog(LOG_ERR, "unable to create %s listener socket: %m", s->name);
        service_forget_exec(s);
        return;
    }
```

... though this sounds like it might be able to result in a situation where the service is successfully "up" on IPv6 but not on IPv4 (or v/v), when you expected both.  I was hoping this would be a simple patch, but this complicate things: if a service is up on one port, but not up on all the ports we expect it to be up on, I think this should also be "exit with error", yeah?  But, off the top of my head, I'm not sure how to accurately determine "all the ports we expect it to be up on" to make that check.

[The behaviour's the same for `open()` and `listen()` failures: log about them individually, then disable the service if we reach the end of the addrinfo loop with no good sockets.]

I'd probably wanna put the "exit on bind failure" behaviour behind an imapd.conf setting, cause it's quite a bit different from the historical default, not sure what to call it though?

**Comment by robn** [comment]
Hmm, interesting. Can you bind a service to multiple ports explicitly (some list incantation like `listen="foo,bar"` or even `listen="foo" listen="bar"` or is it only one, but that might be `*:1234` for all interfaces?

Either way, I would argue that any bind failure means everything should fail, and if you specify `*` and the OS gives you something you didn't ask for, then you get to keep it. But then I think `*` was designed by someone having a laugh. Ambiguity should be met by "please be less ambiguous", not "I do what I want lol".

That said, a config option is probably best, because breaking existing installs would be bad. `abort_on_bind_error:` is my suggestion with zero thought. Or maybe, `abort_on_bind_error=1` as an option in a cyrus.conf `SERVICES` entry, since its really configuration for the supervisor, not the daemons proper? (doesn't bother me; I generate my config).

(It occurs to me that I'm a bad example in a bunch of ways).

**Comment by elliefm** [comment]
> Or maybe, abort_on_bind_error=1 as an option in a cyrus.conf SERVICES entry, since its really configuration for the supervisor, not the daemons proper? (doesn't bother me; I generate my config).

I think this would seem to imply that the abort behaviour would be per-service (e.g. someone might set this flag on their imap service but leave it off their http service), but that feels wrong to me. To the extent that we want it to bail out hard if the bind fails, we really want it to bail out hard, not kinda sometimes do it and sometimes not?  So, I think imapd.conf is the place for it.  Though you're right: it is really config for the supervisor, and we don't seem to have much of that in imapd.conf at the moment.

I need to read and think more about getaddrinfo's result sets because it's been a while since I've had them swapped in, and beyond the simple "loop through until something works" I don't really remember what to expect to be in there

> Can you bind a service to multiple ports explicitly

Off the top of my head, I'm not sure.  It feels like a thing you'd want, but I don't remember seeing it.

> Either way, I would argue that any bind failure means everything should fail, and if you specify * and the OS gives you something you didn't ask for, then you get to keep it.

Hmm yeah, agreed here.  I'm not sure yet whether this behaviour should be only bind errors (what if it binds okay, but then can't listen? what if we don't get as far as bind because the socket call fails?) or anything that meant we didn't get a working socket, but I think this will become clearer once I properly remember what getaddrinfo does

**Comment by elliefm** [comment]
If you're able to play around with this somehow, it'd be good to hear whether it's useful in practice or needs further refinement/design: https://github.com/cyrusimap/cyrus-imapd/pull/2908

**Comment by elliefm** [comment]
This is now in master :)
