### ISSUE TITLE
Non-glibc libc's don't support parameter numbers in printf

### ISSUE THREAD

**Issue by tathougies** [cyrusimap/cyrus-imapd#2925]
The error message for LMTP_OK in lmtp_err.et is

> ec LMTP_OK,
>   "250 2.1.5 Ok SESSIONID=<%2$s>"

When cyrus imap is compiled under alternate libcs (like musl in my case), the server responds with an empty line to the end of `DATA`. I'm guessing this is because musl gives up when it encounters an unknown format number.

I tried making a patch and verified it works, but I'm not sure if this is the right way to solve the issue:

```
diff -ur source/imap/lmtpengine.c source.old/imap/lmtpengine.c
--- source/imap/lmtpengine.c	1969-12-31 16:00:01.000000000 -0800
+++ source.old/imap/lmtpengine.c	2019-11-30 13:29:58.730765423 -0800
@@ -237,7 +237,7 @@
         break;
     }
 
-    prot_printf(pout, error_message(code), error_message(r), session_id());
+    prot_printf(pout, error_message(code), r ? error_message(r) : "Ok", session_id());
     prot_puts(pout, "\r\n");
 }
 
diff -ur source/imap/lmtp_err.et source.old/imap/lmtp_err.et
--- source/imap/lmtp_err.et	1969-12-31 16:00:01.000000000 -0800
+++ source.old/imap/lmtp_err.et	2019-11-30 13:29:45.676892453 -0800
@@ -45,7 +45,7 @@
 # Enhanced Mail System Status Codes (RFC 3463)
 
 ec LMTP_OK,
-   "250 2.1.5 Ok SESSIONID=<%2$s>"
+   "250 2.1.5 %s SESSIONID=<%s>"
 
 ec LMTP_MAILBOX_ERROR,
    "451 4.2.0 %s"
```

**Comment by elliefm** [comment]
The %_n_$ parameter field is a POSIX feature, not a glibc extension.  I don't know when it came into existence, but it's documented at least as far back as POSIX.1-2008.  I can't find a specific statement of supported standards on the musl website, but wikipedia reckons POSIX.1-2008 is supported, so this might be either a bug or missing feature in musl.  Have you reported this to the musl maintainers?  If there is an open ticket, it would be good to have it cross-referenced here.

Your patch looks like an okay workaround, but note that with your change to lmtp_err.et, _every_ piece of code that might ever stringify an LMTP_* error needs to do the same `r ? error_message(r) : "Ok"` juggle, because `error_message(0)` isn't strongly defined (it might be NULL, might be an empty string, might be a string indicating success, might be a string indicating an unknown error code...).  

It's not clear to me whether you've exhaustively audited these cases, and lmtpengine.c:237 was the only occurrence, or whether that's just the only one you've tripped over so far.

At present, I'm disinclined to merge this patch into master because of the ongoing maintenance headache it represents (when there's already a standard POSIX feature for doing exactly what we need).

The good news is, I don't expect the code your patch touches to change much (assuming there's no other cases you haven't caught yet), so you'll probably be able to just keep applying the same patch at your end each time you build.

**Comment by tathougies** [comment]
The other option of course is, if this is indeed POSIX (I wasn't aware), is to patch the libc I'm using (musl in this case). I will see about doing that first.

**Comment by elliefm** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html  See the paragraph starting with "Conversions can be applied to the nth argument..."

Link is to the current version, but I checked the 2008 version after reading up about musl, and it was there in 2008 too.  I didn't check any further back.

**Comment by dilyanpalauzov** [comment]
As part of https://github.com/cyrusimap/cyrus-imapd/issues/3035 imap/lmtp_err.et was updated as requested here in f4b4c5bf65c1737.

**Comment by elliefm** [comment]
Good find, thanks.  Closing this one.
