### ISSUE TITLE
Document requirements for 3.2: libshape and libchardet

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#3007]
According to my notes, collected over the years, without having reference to something specific,

* libchardet was skipped from docsrc/imap/developer/compiling.rst
* likewise for libshape.

libjansson-dev is mentioned in both assets/cyrus-build-devpkg.rst and assets/cyrus-build-reqpkg.rst.  The library is required in 3.0 and optional in 3.2 (according to my notes).

**Comment by dilyanpalauzov** [comment]
Likewise for zeroskip, which is in 3.2 a separate package.  It is not mentioned as requirement for 3.2.

According to docsrc/imap/concepts/deployment/databases.rst only the cyrus.indexed.db can be of type zeroskip, but lib/imapoptions offers zeroskip for annotations_db, backup_db, conversations_db…

**Comment by dilyanpalauzov** [comment]
Zeroskip is not mentioned in docsrc/imap/reference/faqs/feature-database-backend.rst: “Which database backend should I use for which databases?”.

**Comment by elliefm** [comment]
I've updated the compiling docs to mention libchardet and shapelib, thanks

libjansson is mandatory in 3.2, so I've removed it from assets/cyrus-build-devpkg.rst

zeroskip is pretty new and not extensively tested under real load. I'm not sure we want to recommend people use it yet, unless they're willing and able to contribute patches to it?  It would be nice to mention that it exists, so that people with that capacity can know to try it out, but off the top of my head I'm not sure where in the documentation that might slot in.
