### ISSUE TITLE
Regenerate periodically the documentation at www.cyrusimap.org

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#3010]
According to the bottom of https://www.cyrusimap.org/ the documentation was last generated for .3.0.13 in November 2019,  It says also „The latest development version 3.1.9 is at https://www.cyrusimap.org/dev/”.  https://www.cyrusimap.org/dev/ says “This is version 3.3.0-dev0: development branch. The latest stable version 3.2.0-beta3 is at https://www.cyrusimap.org/3.0/. Last updated on Feb 10 2020”. https://www.cyrusimap.org/3.0/ says “This is the documentation for version 3.0.13 (stable) of Cyrus IMAP: stable branch.”.

* Create stable URLs for the 3.0, 3.2, stable and unstable documentations
* State clearly which version is documented at www.cyrusimap.org 
* Regenerate the documentation periodically (monthly or weekly)

**Comment by elliefm** [comment]
The stable URLS for the different versions already exist:

https://www.cyrusimap.org/2.5
https://www.cyrusimap.org/3.0
https://www.cyrusimap.org/3.2
https://www.cyrusimap.org/dev

The top level website is for the current stable version, which at the moment is 3.0.13.  When 3.2.0 comes out of beta, this will change.  The specific-version URLs will continue to work the same.

It says, right at the top of the (stable) main page,

> This is the documentation for version 3.0.13 (stable) of Cyrus IMAP: stable branch.
> The latest development version 3.1.9 is at https://www.cyrusimap.org/dev/.

There has not been a new development snapshot since 3.1.9, so this is correct.  The /dev section of the website refers to 3.3.0-dev0 because the master branch is now 3.3 (not 3.1), but there has not yet been a new dev snapshot since this change occurred.  There won't be one until after 3.2.0 comes out of beta, because we're focused on that.

The website is automatically re-generated hourly.  The timestamp at the bottom of the page is for that page only (not the whole site), and is the timestamp of the last git commit on that page's source rst file.  For example, https://www.cyrusimap.org/imap/reference/faqs/o-annotations.html was last updated a few days ago, cause I fixed a typo.
