### ISSUE TITLE
Deduplicate implicit keep against fileinto in Sieve

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#3023]
If a sieve script does multiple `fileinto` calls that resolve to the same mailbox, Cyrus will deduplicate and only do the *last* one (the order is important, because the keywords may be different at the time of the different `fileinto`s). This is perfect. However, it does not do the same with the implicit keep mailbox. If you have `fileinto :copy INBOX` for example, and the implicit keep is not cancelled later on, Cyrus will attempt to deliver two copies to that mailbox. Delivery deduplication on the Message-Id, if turned on, will cause the latter copy to be discarded, but this is different behaviour to duplicate fileintos (because you get the keywords of the earlier copy). Instead, the implicit keep should be treated like a `fileinto` and replace any previous `fileinto` to the same mailbox (so you get the keywords at the time of the implicit keep, not the earlier fileinto).

**Comment by ksmurchison** [comment]
Just so I'm clear, you always want the final keep/fileinto "INBOX" action to win, regardless of whether its implicit or explicit, correct?

**Comment by neilj** [comment]
Correct.

**Comment by ksmurchison** [comment]
I assume that we want to take into account fileinto :specialuse and :maillboxid as well?  What about fileinto :specialuse :create?

**Comment by ksmurchison** [comment]
@brong  I'm thinking that the fileinto and keep callbacks each need to be split into a "what mailbox does the action resolve to and can we deliver to it piece" and a "go ahead and deliver to the mailbox piece".  By doing this, we will have the final mailbox name to use for comparison when creating the action list and we will know that 
fileinto "INBOX.foo"
fileinto :mailboxid "id-of-foo"
fileinto :specialuse "\\foo"
keep (user+foo)
all resolve to user.user.foo

similarly
fileinto "INBOX"
keep (user+nonexistent_mailbox)
both resolve to user.user

otherwise, I don't see how we can catch all instances of duplicate delivery before we do the deliver.db checks

**Comment by ksmurchison** [comment]
Should be fixed by https://github.com/cyrusimap/cyrus-imapd/pull/3024
