### ISSUE TITLE
python in configure

### ISSUE THREAD

**Issue by falon** [cyrusimap/cyrus-imapd#3036]
Hello, in `configure` script of 3.2.0 source release I see:
```
    if test -z $PYTHON;
    then
        if test -z "python2";
        then
            PYTHON="python3"
        else
            PYTHON="python2"
        fi
    fi
    PYTHON_NAME=`basename $PYTHON`
```

In line 27301 maybe you would mean:
```
if test -z `which python2`;
```
otherwise always python2 will be selected as python interpreter.

**Comment by elliefm** [comment]
This configuration is not "choosing between python version 2 and python version 3", it is "making sure python version 2 exists".

The 2/3 switching in the generated script is simply because the module that we use for checking for python is capable of checking for either version:
https://www.gnu.org/software/autoconf-archive/ax_python_module.html

But there is a typo in our usage: per its own documentation, we should be calling it with "python" as the third argument to look for python version 2, not "python2".  So I'm fixing that up now.

**Comment by falon** [comment]
Sorry If I'm back on this issue.
It's ok. I would only remind that Python2 is no more supported, it reached its EOL. Why don't trust on Python3?

**Comment by elliefm** [comment]
None of us are python developers, and none of us are up to date on the python2/python3 switchover status.  We're simply using what already works.

In the past, and if I recall correctly, the version of python-sphinx that we had on the server that built the Cyrus website required python2.  This may have changed.  (We no longer use that specific server, but I do not know offhand what is on the new build server.)

I would be happy to accept a pull request that converts Cyrus to prefer python3 if it's available, _if_ it also clearly documents the new minimum versions of each of the python packages we need.  We wouldn't be able to merge it until the current website build server has been confirmed or updated as necessary to work correctly with it (since the website build is entirely automated), but even a dangling pull request would be a step forward! :)

It's a fairly low priority -- we distribute Cyrus with all the docs already built, so the doc build dependencies are only needed for people building from git.
