### ISSUE TITLE
Active connections metrics miscalculated on TLS services

### ISSUE THREAD

**Issue by ludovicm67** [cyrusimap/cyrus-imapd#3039]
`cyrus_*_active_connections` on TLS services decreases on connection end, but only increases when the TLS handshakes finishes, resulting to negative values.

For example, opening a TCP connection to a TLS service with `nc` without doing any TLS handshake does not increase the active connection count, but decreases on connection end.

Affected metrics, with a standard cyrus imap config, on v3.2.0:

 - `cyrus_imap_active_connections{service="imaps"}`
 - `cyrus_http_active_connections{service="https"}`

**Comment by elliefm** [comment]
Interesting! Have you noticed whether this also affects "cyrus_lmtp_active_connections"?  Or only imap/http?

**Comment by elliefm** [comment]
Looks like lmtpd isn't affected, because it doesn't offer an '-s' option, unlike imapd and httpd.

**Comment by elliefm** [comment]
Though, if lmtpd was configured with an invalid argument, the fatal usage error each time it starts would produce a similar effect

I'll have a patch for this ready shortly, but am also thinking about whether I can make a regression test for it

**Comment by elliefm** [comment]
These two commits should sort it out, but I'll see if I can get a test going before I merge them properly: https://github.com/cyrusimap/cyrus-imapd/compare/cyrus-imapd-3.2...elliefm:v32/3039-prom-count-fixes

**Comment by elliefm** [comment]
When lmtpd exits early due to a bad command line argument, it doesn't call fatal(), but instead hard exits.  So I can't simply exploit this behaviour to create a test case to reproduce the decrement-without-increment situation.  Dammit.

I think the only way to reproduce this from Cassandane will be to actually have it set up a tls service and then make a plain-text connection to it.  But this will mean adding infrastructure to Cassandane to support setting up tls services, because it currently can't.

**Comment by elliefm** [comment]
Okay that wasn't as hard as I expected.  I now have a test that reproduces the original problem, and proves the fix works.

It's late now and I'm tired, so I won't merge either just yet, until I've given them another look-over when fresh.

**Comment by elliefm** [comment]
This is now fixed on cyrus-imapd-3.2 and master branches, and the fix will be included in the 3.2.1 release.  Thanks for the report :)
