### ISSUE TITLE
cyrus 3.2 sieve smtpclient uses <<>> as sender, MTA rejects

### ISSUE THREAD

**Issue by slangenhorst** [cyrusimap/cyrus-imapd#3057]
Hi,

with cyrus 3.2 my servers stopped sending vacation or forward-messages.
The issue seems to be in smtpclient.c.

lmtp_sieve.c and nntpd.c are using 
smtp_envelope_set_from(&sm_env, "<>");

when sending the mail write_addr in smtpclient.c gets called:
buf_printf(&sm->buf, "%s:<%s>", cmd, addr->addr);

So we end up with MAIL FROM: <<>> which my MTA (Exim) rejects as invalid sender (which seems appropriate).
I don't know when it broke, last knowing working version was 3.0.13.

It could either be fixed by using 
smtp_envelope_set_from(&sm_env, "");
instead or, if you want to use "<>" since it is better readable, a filter in smtpclient like (sorry, my c-skills are rather poor):

`Index: cyrus-imapd-3.2.1/imap/smtpclient.c`
`===================================================================`
`--- cyrus-imapd-3.2.1.orig/imap/smtpclient.c    2020-06-02 12:49:11.645154834 +0200`
`+++ cyrus-imapd-3.2.1/imap/smtpclient.c 2020-06-02 12:49:50.177237275 +0200`
`@@ -868,7 +868,11 @@`
` {`
`     smtp_params_fini(&env->from.params);`
`     free(env->from.addr);`
`-    env->from.addr = xstrdup(addr);`
`+    if (strcmp(addr, "<>") == 0){`
`+        env->from.addr = "";`
`+    } else {`
`+        env->from.addr = xstrdup(addr);`
`+    }`
`     return &env->from;`
` }`

**Comment by elliefm** [comment]
Looks like this affects master too. It was introduced when our legacy sendmail API was replaced in 3.1.3, so it doesn't affect 3.0 or earlier.

I'm inclined to go with the `""` option, since `"<>"` is not actually a magic value, it's simply the smtp syntax for expressing an empty address, and presumably someone working on Cyrus's smtpclient code can just learn that if they didn't already know it.

The bigger part of this work will be adding a regression test for it, since we don't seem to have any tests for smtpclient!  (I think we have some tests that exercise it incidentally, but none that do so specifically.)

**Comment by slangenhorst** [comment]
"" is what i used and it works fine.

**Comment by elliefm** [comment]
Confirmed in Cassandane telemetry:

```
>1591924461>MAIL FROM:<<>> AUTH=cassandane SIZE=465
```

But the minimal smtpd that Cassandane sets up accepts this rubbish, which is why we don't notice that it's bad!

**Comment by elliefm** [comment]
WIP is here: https://github.com/cyrusimap/cyrus-imapd/compare/cyrus-imapd-3.2...elliefm:v32/3057-bad-mail-from

But I'm sidetracked wrestling with Cassandane, cause I found an annoying bug there while testing this

**Comment by elliefm** [comment]
This is now fixed in git, and will be included 3.2.2
