### ISSUE TITLE
Issue with configure and Xapian CJK support

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#3073]
There seems to be an issue with configure and Xapian. I have Xapian 1.4.14, but the CJK check fails:

```
configure:20322: checking for Xapian cjk word tokenization
configure:20335: g++ -o conftest -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection   -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/lib64 -lxapian conftest.cpp   >&5
conftest.cpp: In function 'int main()':
conftest.cpp:73:45: error: 'FLAG_CJK_WORDS' is not a member of 'Xapian::TermGenerator'
 unsigned cjk_flags = Xapian::TermGenerator::FLAG_CJK_WORDS | Xapian::QueryParser::FLAG_CJK_WORDS | Xapian::MSet::SNIPPET_CJK_WORDS; (void) cjk_flags;
                                             ^~~~~~~~~~~~~~
conftest.cpp:73:83: error: 'FLAG_CJK_WORDS' is not a member of 'Xapian::QueryParser'
 unsigned cjk_flags = Xapian::TermGenerator::FLAG_CJK_WORDS | Xapian::QueryParser::FLAG_CJK_WORDS | Xapian::MSet::SNIPPET_CJK_WORDS; (void) cjk_flags;
                                                                                   ^~~~~~~~~~~~~~
conftest.cpp:73:114: error: 'SNIPPET_CJK_WORDS' is not a member of 'Xapian::MSet'
 unsigned cjk_flags = Xapian::TermGenerator::FLAG_CJK_WORDS | Xapian::QueryParser::FLAG_CJK_WORDS | Xapian::MSet::SNIPPET_CJK_WORDS; (void) cjk_flags;
                                                                                                                  ^~~~~~~~~~~~~~~~~
configure:20335: $? = 1
...
configure:20350: Your Xapian does not support CJK word tokenization. Consider installing a recent Xapian >= 1.4.11
```

Either the check is wrong in some way, or the wording in the warning needs to be changed.

**Comment by elliefm** [comment]
How was Xapian built, maybe it was built without CJK support?  In which case, when configure probes it for CJK support it doesn't find it, even though the version is new enough?

**Comment by hagedose** [comment]
I don't know. The package is this one:

https://centos.pkgs.org/8/epel-x86_64/xapian-core-1.4.14-1.el8.x86_64.rpm.html

I installed the SRC RPM, but the SPEC file doesn't mention CJK at all. Regardless, even if that's the reason, the wording should be changed. The simplest fix would be to have it say

`Your Xapian does not support CJK word tokenization. Consider installing a Xapian version that supports it if you need CJK support.`

**Comment by elliefm** [comment]
Oh: it looks like Xapian's CJK word tokenisation support is only on the xapian master branch at the moment, and is not in any of the 1.4 releases (and, I guess it probably won't be, otherwise it probably would've been by now).

Note that "CJK word tokenisation support" is not the same thing as "CJK support".  Your version of Xapian supports CJK languages, but (with a very big handwave here) it doesn't support tokenising on "words" in these languages.  In this situation, Cyrus is simply configuring itself to use "ngrams" instead of "words" for CJK tokenisation.  Sorry I can't explain the ramifications of this distinction, I don't understand it myself.

The ngram tokenisation looks like it has existed for quite a while (back to 1.2.something, anyway).  But you will get the superior "words" tokenisation support if you install 1.5 or later, which at the moment I think you can only get by building xapian yourself from git or a dev snapshot.

w.r.t. this notice specifically, I think I'm going to change it to something like:

> Your Xapian does not support CJK word tokenization.  CJK ngram tokenization will be used instead.

What do you think?

We don't actually do a version check anywhere, we just look for "words" support, and if that's not available, then we assume "ngrams" is.  

I don't know what requirement the ">= 1.4.11" refers to.  It might be some other thing that we need, unrelated to CJK support, that prevents us recommending earlier versions than this.  Or it might have been a historical guess at when the "words" support would eventually be released.  Separately to the tokenisation detection, we should probably also do a version check for whatever the absolute minimum version we support it, so that the configure can actually fail early if the Xapian it finds is too old for us.  But I don't know what that absolute minimum version is, so this part will take a while longer (our Xapian expert is on leave at the moment).

**Comment by hagedose** [comment]
Your suggestion sounds fine to me.
