### ISSUE TITLE
httpd 100% CPU after using Thunderbird CalDAV client with HTTP/2

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#3180]
Reported on Debian bug tracker.  From discussion on tracker, seems to be worked around by disabling HTTP/2 in Thunderbird, suggesting the problem is limited to HTTP/2 specifically.

[Debian Bug 969222: cyrus-caldav: hhtp keep 100% CPU after access with Thunderbird](https://bugs.debian.org/969222)

_Originally posted by @guimard in https://github.com/cyrusimap/cyrus-imapd/issues/3152#issuecomment-691691362_

**Comment by guimard** [comment]
Hi @elliefm, thanks for taking care of this. Do you think it could be linked to this issue : [Missing temporary directories](https://bugs.debian.org/969261) ? I fixed this one in version [debian/3.2.3-2](https://packages.debian.org/source/unstable/cyrus-imapd) _(issue was due to a [Debian/dh_installtmpfiles](https://dyn.manpages.debian.org/unstable/debhelper/dh_installtmpfiles.1.en.html) change)_

**Comment by guimard** [comment]
_(I don't think so but...)_

**Comment by guimard** [comment]
Did you succeed to reproduce this bug ?

**Comment by ksmurchison** [comment]
I'm pretty sure that this cherry-picked commit will fix the issue
https://github.com/cyrusimap/cyrus-imapd/commit/2696ed7219eacbe42e1b11c4f9fbdf61be21b82d

**Comment by guimard** [comment]
Hi @ksmurchison,
I'm not directly able to test it but I can push the patch

**Comment by dilyanpalauzov** [comment]
The problem report is about HTTP/2 not correctly functioning on the 3.2 branch when CalDAV/CardDAV is called from Thunderbird.

A patch was provided to the 3.2 branch.  The reporter (some Debian user) can neither confirm nor deny, that the provided patch resolved the problem.

As a matter of fact this is tracked for Debian at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969222 and it states since 25th October:
> ... We believe that the bug you reported is fixed in the latest version of cyrus-imapd
> …    * Import upstream fix to close properly HTTP/2 connections (Closes: #969222) and re-enable HTTP/2


As far as the current case is not actionable, I propose closing it.

**Comment by elliefm** [comment]
Seems reasonable.  If we receive further feedback that it's not actually fixed, it can always be reopened

**Comment by pimzand** [comment]
I'm seeing the exact same thing in Fedora cyrus-imapd-3.2.4-5.fc34.x86_64
So this means the issue was fixed by Debian, not upstream?

**Comment by elliefm** [comment]
The fix was included in 3.2.5, so the Fedora 3.2.4 package would not include it unless the package maintainer backported it themselves.

**Comment by pimzand** [comment]
Reported to Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1989686
