### ISSUE TITLE
Fix for CVE-2017-14230 missing from 2.5 branch

### ISSUE THREAD

**Issue by hhoffstaette** [cyrusimap/cyrus-imapd#3241]
Commit [6bd33275368e](https://github.com/cyrusimap/cyrus-imapd/commit/6bd33275368edfa71ae117de895488584678ac79) was a fix for [CVE-2017-14230](https://cve.circl.lu/cve/CVE-2017-14230), but apparently was only made on the 3.0 branch. It should probably be applied to 2.5 as well since it is security-relevant.

**Comment by elliefm** [comment]
That commit was a fix for #2132, not for the CVE.  The CVE entry didn't exist until after the fix was released.  I don't think we created the CVE entry, but I can't tell who did.

According to #2132, the problem didn't exist in 2.4.12, and the code wasn't changed for 2.5.

So as far as I can tell at the moment, the problem was probably introduced in 3.0.0-beta1 by a0ca3af7b54, which substantially refactored this code.

The fix in 6bd33275368e depends on the refactor in a0ca3af7b54, so it can't simply be applied to 2.5 as well.  If the problem demonstrably exists in 2.5, it will need to be patched independently.  But given that it didn't exist in 2.4.12, and the code here didn't change until 3.0.0-beta1, I don't think 2.5 is affected.

**Comment by hhoffstaette** [comment]
So apparently I misread the Gentoo security announcement, which at the time only mentioned the problem to be
in "< 3.x", ignoring the fact that 2.x didn't have the bug. Since I don't have an easy reproducer I'm closing this.
Thanks for the explanation and sorry for the noise.
