### ISSUE TITLE
Error sending emails via JMAP protocol.

### ISSUE THREAD

**Issue by zvasilev** [cyrusimap/cyrus-imapd#3559]
Error sending emails via JMAP protocol.
My integration tests against the official FastMail server have started to return bugs recently.

I tried to re-create the app password, but without success.
I guess it is related to this feature (https://github.com/cyrusimap/cyrus-imapd/issues/2433).

Everything works OK via SMTP, but via JMAP Email / submission the following error is returned.

request:
{"methodCalls":[["EmailSubmission/set",{"accountId":"u606140f3","create":{"5591af66-f1ec-415c-c9af-8d16de1229c7":{"emailId":"M9c5250fc1c4b156d788a3c40","envelope":{"mailFrom":{"email":"my_email@mailtemi.com"},"rcptTo":[{"email":"my_email@mailtemi.com"}]},"identityId":"c5502a8d-0848-cabe-7ee9-c9945bfced80"}},"onSuccessUpdateEmail":{"#5591af66-f1ec-415c-c9af-8d16de1229c7":{"keywords/$draft":null,"keywords/$seen":true,"mailboxIds/ec30887f-4f4b-4d11-9602-4699e9ad15b3":true}}},"gTYpgw==#1"]],"using":["urn:ietf:params:jmap:core","urn:ietf:params:jmap:mail","urn:ietf:params:jmap:submission"]}

The response is:
{"accountId":"u743140b1","created":null,"destroyed":null,"newState":"27282","notCreated":{"766cd8ef-7e69-aeae-a5c2-51bbecfbe5c2":{"description":"User not permitted to send with this from address (unverified header)","type":"forbiddenFrom"}},"notDestroyed":null,"notUpdated":null,"oldState":"27282","updated":null}

**Comment by elliefm** [comment]
I'm assuming you've masked your real from address in the report (sensible!)

"User not permitted to send with this from address (unverified header)" -> I think this error is from the Fastmail middleware rather than from Cyrus, and I think it's saying that you don't have a verified "Sending Identity" for the address you're trying to send from.  You might be able to just create one in your Fastmail settings, and then it should work.

If that doesn't fix it, please contact Fastmail support, that way you'll reach someone who can investigate it. :)
