### ISSUE TITLE
Unit test aaa-db:test_multiopen fails for lmdb 0.9.29

### ISSUE THREAD

**Issue by buschmann23** [cyrusimap/cyrus-imapd#3641]
The unit test from cyrus-imapd 3.0.16 works fine with lmdb 0.9.17 but fails with lmdb 0.9.29 writing the following output:
```
Suite: aaa-db
  Test: openclose ...[backend=skiplist] [backend=flat] [backend=twoskip] [backend=lmdb] passed
  Test: multiopen ...[backend=skiplist] [backend=flat] [backend=twoskip] [backend=lmdb] 
unit: fatal(Internal error: assertion failed: lib/cyrusdb_lmdb.c: 208: db && tid)

unit: code under test (/home/abuild/rpmbuild/BUILD/cyrus-imapd-3.0.16/cunit/aaa-db.testc:test_multiopen) exited with status 1
FAILED
    1. ./cunit/aaa-db.testc:310  - CU_ASSERT_EQUAL(r=-4,CYRUSDB_OK=0) [backend=lmdb]
    2. ./cunit/aaa-db.testc:310  - CU_ASSERT_PTR_NOT_NULL(txn) [backend=lmdb]
    3. cunit/unit.c:115  - CU_FAIL_FATAL("Code under test exited")
```

**Comment by elliefm** [comment]
That's not surprising really.  We never did manage to get lmdb working reliably in practice, and  support for it was eventually removed entirely in 3.2.0.

I would recommend using twoskip instead of lmdb.  You can use [cvt_cyrusdb](https://www.cyrusimap.org/3.0/imap/reference/manpages/systemcommands/cvt_cyrusdb.html) to convert your existing lmdb databases, if you have any.

In 3.0 the lmdb support isn't compiled by default, but only when the `--with-lmdb` argument is provided to `configure`.  I see from the "rpmbuild" in the output that you're possibly building from an rpm, so I'm not sure exactly what you need to do to reconfigure and start again, but hopefully you do.

Once configured without lmdb support, the aaa-db suite will no longer try to use it, and therefore no longer fail.

**Comment by buschmann23** [comment]
Thank you for the information. Yes, I am building RPM packages for openSUSE distributions. I now disabled lmdb support.
