### ISSUE TITLE
Missing manual pages

### ISSUE THREAD

**Issue by prlw1** [cyrusimap/cyrus-imapd#3843]
I believe your intention is that if cyrus imapd is built without certain options, e.g., NNTPD, then the manual pages which are dependent on those options, e.g., fetchnews.8, shouldn't be installed.

Thankfully, you also don't expect me, when building from your tarball, to install manual page building dependencies, to generate them from `.rst` files in docsrc.

The inconsistency is that when you `make dist`, without enabling all of the options, those pregenerated manual pages don't make it into the tarball, as the `dist` part of `dist_man8_MANS` would have to be outside of any conditions.

**Comment by elliefm** [comment]
Should be fixed in future releases from 3.2 forward.

The fix doesn't cherry-pick cleanly to 3.0 -- there have been other changes in the meantime.  If someone is affected by this on 3.0 and reopens the issue, I'll be happy to spend a little effort backporting it to fix 3.0 too.  But if that doesn't happen, I'll save my energy.
