### ISSUE TITLE
smmapd ignores userdeny database

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#3862]

**Comment by elliefm** [comment]
I see you're working on #3863 to update the documentation to describe this problem.

I don't know much about smmapd.  I'm not sure if smmapd ignoring userdeny was some oversight that should be fixed, or a deliberate choice...

My vague understanding is you use userdeny to lock people out from logging in and accessing their mail, even though they do have an account on disk.

I guess you might use this for people who have left the organisation and no longer have a mail account, though their mail still might exist on disk for data retention/auditing purposes.  In which case, sendmail rejecting incoming mail would make sense.

But I guess you might also use it for locking users out who have had their password/account stolen, until they change their password.  In which case, it would be nice for sendmail to still accept incoming mail for them, so that when they regain access they haven't missed any mail.

I wonder if this behaviour should be configurable

**Comment by dilyanpalauzov** [comment]
Userdeny is used by lmtpd, and can disable delivery of new messages to an account by lmtpd. Userdeny is used by imapd to disable IMAP access to the account.

The use case is to have CalDAV only account, which does not accept emails (and does no scheduling).  When emails for such accounts are sent, smmapd is supposed to look in the userdeny database and say, that emails for the account cannot be delivered, just like lmtpd does it.

**Comment by dilyanpalauzov** [comment]
https://github.com/cyrusimap/cyrus-imapd/pull/4908
