### ISSUE TITLE
Internal error: assertion failed: imap/message.c: 4286: !message_need(m, M_RECORD)

### ISSUE THREAD

**Issue by jikamens** [cyrusimap/cyrus-imapd#3869]
This was discussed at length in [bug 2171](https://github.com/cyrusimap/cyrus-imapd/issues/2171), which was closed several years ago.

I'm seeing this issue now in Linux, CentOS 8, x86_64, with cyrus-imapd 3.0.7.

Both imapd and reconstruct are running into it.

Please advise.

**Comment by dilyanpalauzov** [comment]
It is unlikely that somebody will investigate this, if it happens only in the 3.0 series and no clear stepts are provided how to reproduce the problem.

**Comment by elliefm** [comment]
Looks like #2171 was closed because according to 
https://github.com/cyrusimap/cyrus-imapd/issues/2171#issuecomment-353797105 the problem went away when they ran `reconstruct -V max`, as advised by the upgrade documentation.

Did you recently upgrade to 3.0.7?  Did you also miss this step?

If you did recently upgrade, 3.0.7 is a strange choice.  There have been multiple security fixes and a data loss bug fix for 3.0 since then -- the current version of the 3.0 series is 3.0.15.  I assume your choice of 3.0.7 is based on a vendor package, in which case you should check with the vendor whether they have backported the fixes from 3.0.8-3.0.15.

For whatever it's worth, the current stable version is 3.4.2.  You should consider running that, if you can.

**Comment by jikamens** [comment]
Hi,

My impression from reading #2171 was tht `reconstruct -V max` was a workaround, rather than something addressing the root cause. From the subsequent discussion in that ticket it appeared to me that there was a belief that the root issue had been resolved at some point, which is why I felt it appropriate to open an issue issue about it, to let the developers know that, at least as of 3.0.7, which is newer than the version discussed in #2171, the issue was not fixed.

Yes, I was able to clean up most of the crashes by running `reconstruct -V max`, but I had to run it many times to get it to run all the way through, since it got interrupted over and over by the assertion failure. So that seems to me to indicate that there is still room for improvement.

I am using 3.0.7 because that is the version shipped with CentOS Stream 8 and I would rather not deviate from vendor packages. A number of fixes from newer releases have been backported into the CentOS Cyrus packages.

If this report is not useful, feel free to close it. I was just trying to be helpful. :shrug:

**Comment by elliefm** [comment]
Thanks

It sounds to me like the root cause was that the index files were old enough to be missing a field that the newer version couldn't function without, and running `reconstruct -V max` to rebuild the index files for the current version was the correct solution.
