### ISSUE TITLE
2.4.17 => 3.2.6: new messages not updated in Inbox for certain IMAP clients 

### ISSUE THREAD

**Issue by stfast** [cyrusimap/cyrus-imapd#3897]
After migrating mailboxes (XFER) from cyrus-imapd 2.4.17 to 3.2.6 there is an issue with IMAP clients Outllook 2013+,
Thunderbird, eM Client, not getting new messages in Inbox after Get Messages/Send/Recieve. 

However new messages for these clients are updated on startup, when NOOP is submited to server, otherwise there are no NOOPs on Get Messages/Send/Recieve. Works also in Windows Outlook, when you change focus back to Inbox folder.

There aren't any issues with Apple Mail, Roundcube webmail, iPhone, Android, macOS Outlook 2019, tested so far. 

Could it be something I missed in imapd.conf or is a new default.

**Comment by stfast** [comment]
This issue is solved with reconstruct -V option immediately.

[cyrus@cyrus1 ~]$ reconstruct -V max
user/fast@ftp.net
Converted user/fast@ftp.net version 6 to 16
user/fast/mbox1@ftp.net
Converted user/fast/mbox1@ftp.net version 6 to 16
user/fast/ASK_Triglav/mbox1@ftp.net
Converted user/fast/mboc0/mbox1@ftp.net version 6 to 16
user/fast/Apple Mail To Do@ftp.net
Converted user/fast/Apple Mail To Do@ftp.net version 6 to 16
user/fast/Archive@ftp.net
Converted user/fast/Archive@ftp.net version 6 to 16
user/fast/Companies@ftp.net
.....

One would expect, that this happens on XFER.

Any comments why cyrus.index version would have impact on client operability?

**Comment by elliefm** [comment]
cyrus.index stores metadata that the code needs to function.  If those clients were doing things for which Cyrus's implementation requires that metadata, and it did not have that metadata because the cyrus.index was the wrong version, then you would expect it to not be able to do those things correctly or perhaps at all.

Presumably these things worked fine in the older version because that was before the code came to rely on that metadata being in the index.

> One would expect, that this happens on XFER.

Yes, it does, if the source server is new enough to recognise the destination server's version.  If it does not recognise the destination server's version, it will _downgrade_ the cyrus.index to the oldest known version, just in case, which is version 6.  It looks like this is what has happened here.

The [3.2 upgrading instructions ](https://www.cyrusimap.org/3.2/imap/download/upgrade.html#special-note-for-murder-configurations) say:

> If you are upgrading from 2.4, and wish to use XFER to transfer your mailboxes to your new 3.2 server, please consider first upgrading your 2.4 setup to version 2.4.19 or later. Earlier versions of 2.4 do not correctly recognise the 2.5 and later mailbox versions, and will downgrade mailboxes (losing metadata) in transit. 2.4.19 and later versions correctly recognise 2.5 and later servers, and will not downgrade mailbox versions in transit.

So the reason this happened is because you used XFER to go from 2.4.17 to 3.2, and the 2.4.17 server cannot recognise 3.2 because 3.2 did not exist when 2.4.17 was released.

Even if you had upgraded to 2.4.19 first, you would still have needed to `reconstruct -V max` afterwards, but at least then you wouldn't _lose_ metadata in the process, you would only be missing stuff you never had to begin with.

**Comment by dilyanpalauzov** [comment]
Can this be closed?
