### ISSUE TITLE
Unable to build 3.6-beta1

### ISSUE THREAD

**Issue by guimard** [cyrusimap/cyrus-imapd#3934]
Hi,

when trying to build 3.6-beta1, I got this error _([see Debian job](https://salsa.debian.org/debian/cyrus-imapd/-/jobs/2501973))_:
```
checking for libical >= 3.0.0... yes
checking for icalproperty_new_color in -lical... yes
checking for icalrecurrencetype_rscale_is_supported in -lical... yes
checking for icalcomponent_clone in -lical... no
checking for ical_set_invalid_rrule_handling_setting in -lical... no
[...]
External dependencies:
   ldap:               yes
   openssl:            yes
   zlib:               yes
   jansson:            yes
   pcre:               yes
   clamav:             yes
   -----------------------
   caringo:            no
   openio:             no
   -----------------------
   nghttp2:            yes
   wslay:              no
   brotli:             yes
   zstd:               yes
   xml2:               yes
   ical:               yes
   shapelib:           yes
   icu4c:              yes
   chardet:            no
   cld2:               no
[...]
/usr/bin/ld: imap/.libs/libcyrus_imap.so: undefined reference to `icalcomponent_get_component_name'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:4587: imap/imapd] Error 1
```

**Comment by guimard** [comment]
My libical is 3.0.14 which looks to be the last available

**Comment by elliefm** [comment]
Interesting, it might be dependent on the bleeding edge libical from https://github.com/cyrusimap/cyruslibs

Ahh yep, looks like this function was added in https://github.com/libical/libical/commit/e412005c3da06fb799b373643991e6dbb038307d and it's expected to be included in libical 3.1.0, which doesn't exist yet.

@ksmurchison any chance we can conditionalise the code that uses this function, or provide a fallback implementation within Cyrus, so that people can run Cyrus 3.6 without needing a libical version that doesn't exist yet?  Looks like it's only used once, here:

https://github.com/cyrusimap/cyrus-imapd/blob/4faa01f47756cd2799519094ccc4cc8e1c32d8c8/imap/ical_support.c#L1844-L1848

@guimard I wonder if there are more problems like this.  Are you able to build with `make -k`, so that it keeps going and reports all build errors, rather than stopping at the first one?  If there's a bunch of build errors, it might save us some time if we can see and address them all at once, rather than not seeing the next one until the first is fixed!

**Comment by guimard** [comment]
Thanks @elliefm. Here is the [make -k](https://salsa.debian.org/debian/cyrus-imapd/-/pipelines/352856) job

**Comment by guimard** [comment]
I don't see any new error, just this one 2 times.

https://salsa.debian.org/debian/cyrus-imapd/-/jobs/2508623

**Comment by elliefm** [comment]
I've picked the fix from #3938 to the cyrus-imapd branch, so this will be fixed in 3.6.0-beta2

**Comment by guimard** [comment]
Thanks @elliefm: build [succeeded for all architectures](https://buildd.debian.org/status/logs.php?pkg=cyrus-imapd&ver=3.6.0~beta2-1) !

**Comment by elliefm** [comment]
Awesome, thanks for the update!
