### ISSUE TITLE
Cyrus SASL for CentOS 7.9 is exposed to security vulnerabilities

### ISSUE THREAD

**Issue by meyrevived** [cyrusimap/cyrus-imapd#4174]
Hello,
My name is Meirav Rath, I'm a software developer and security champion at Imperva.
As part of our effort to map security risks in our products I've been scanning our 3rd party rpms for vulnerabilities. It looks like Cyrus SASL for CentOS 7.9 (Cyrus version 2.1.26) is vulnerable to [CVE-2019-19906](https://nvd.nist.gov/vuln/detail/CVE-2019-19906).

When can we expect an RPM with an updated version fixes for this issues, aimed for CentOS7.9?

Thanks.

**Comment by elliefm** [comment]
Hi,

This is the repository for Cyrus IMAP.  The repository for Cyrus SASL is at https://github.com/cyrusimap/cyrus-sasl

That said, as far as I know the Cyrus SASL project does not provide RPM packages directly.  You will probably need to contact the maintainer of the CentOS package, rather than the upstream project.  I don't know who that is, but maybe you could ask on the Cyrus SASL mailing list.

Mailing list details are available here: https://www.cyrusimap.org/imap/support/feedback-mailing-lists.html

Hope this helps! :)
