### ISSUE TITLE
[2.5.9] murder frontend mailboxes.db bottleneck

### ISSUE THREAD

**Issue by MASHtm** [cyrusimap/cyrus-imapd#43]
After upgrading to 2.5.9 on our frontends we see a bottleneck with mailboxes.db access.

Our three machines had a constant load of 1-2 with 2.4. After upgrading to 2.5.9 and conversion to twoskip we had 100-250. After reconversion to skiplist we still have 10-20, but at least usable servicelevels.

After many hours of searching it seems that the access to mailboxes.db is somehow more expensive with 2.5.9. Since lmtpd was changed to ask the local database as well instead of the mupdate server this load was added, too.

The local mupdated on our frontends waits up to 5-10 seconds for a writelock on skiplist. With twoskip we saw no changes to mailboxes.db in 1,5 hours at all.

Our mailboxes.db has ~1.2 million entries and 125MB size with skiplist (~150 with twoskip). A "LIST" command on our frontends currently takes about 1 second.

One way i can think of to reduce load on mailboxes.db is to "proxy" LIST and XLIST to the backends like "LSUB" or "return (SUBSCRIBED)". XLIST has to be proxied anyway to get the special-use metadata as reported before.

Maybe asking the local mupdated can help as well to have only some threads accessing mailboxes.db. Maybe mupdated can cache entries?

**Comment by MASHtm** [comment]
A small addon:

We did not dump/undump our mailboxes.db and we still use
improved_mboxlist_sort = false

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
