### ISSUE TITLE
BINARY FETCH and x-uuencode

### ISSUE THREAD

**Issue by alecpl** [cyrusimap/cyrus-imapd#4567]
I'm not sure Cyrus does not support uuencoded parts at all, but the behavior I see is wrong anyway.

```
C: A0008 UID FETCH 31 (BINARY.PEEK[2])
S: * 2 FETCH (UID 31)
S: A0008 OK Completed (0.000 sec)
```

So, it does not return the body nor an error. Dovecot when it can't decode a content returns `NO [UNKNOWN-CTE]` or `NO [PARSE]`. I suppose, if I don't see `BINARY[2]` in the response I could consider this an error condition and fallback to use non-binary FETCH, but a `NO` response would be better. Of course, it would be even better to make it just work.

And another issue with a non-UID FETCH.
```
C: A0008 FETCH 2 (BINARY.PEEK[2])
S: A0008 NO No matching messages (0.000 sec)
C: A0009 FETCH 2 (BODY.PEEK[2])
S: * 2 FETCH (BODY[2] {4272}
...
```
So the response is wrong, again.

Here's the sample message [test_message_uuencode_bug.txt](https://github.com/cyrusimap/cyrus-imapd/files/12326844/test_message_uuencode_bug.txt)

Tested with Cyrus IMAP 3.6.0.

**Comment by elliefm** [comment]
https://www.ietf.org/rfc/rfc9051.html#name-fetch-response says, for BINARY and BINARY.SIZE:

> If the server does not know how to decode the section's Content-Transfer-Encoding, it **MUST** fail the request and issue a "NO" response that contains the "UNKNOWN-CTE" response code.

I assume this applies to BINARY.PEEK too, but haven't bothered to find a citation.

So you're right.  We don't seem to support Content-Transfer-Encoding: x-uuencode, but our FETCH response is wrong because the NO doesn't specify the UNKNOWN-CTE response code, and our UID FETCH response is also wrong because it says OK.

**Comment by elliefm** [comment]
I don't see a test that would indicate we've already fixed this in a later version, so for now I'm labelling it as if it affects later versions too.
