### ISSUE TITLE
CI always fails

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#4922]
On each PR github sends an email with subject “Run failed: Cyrus IMAP CI  - branch (commit-id)” and content: “
Cyrus IMAP CI: All jobs have failed… “View workflow run” - with a hyperlink e.g. to https://github.com/dilyanpalauzov/cyrus-imapd/actions/runs/9147022674 .”

There is nothing, which can be done, once the email arrives.

• Do something so these emails are not sent anymore after each PR.

**Comment by elliefm** [comment]
That's weird...

I see lots of failures in the github actions on your fork: https://github.com/dilyanpalauzov/cyrus-imapd/actions/workflows/main.yml

But the equivalent URL on my fork is a 404:
https://github.com/elliefm/cyrus-imapd/actions/workflows/main.yml

So github actions are running on your fork, but not on mine.  I wonder why?

The master branch on my fork is ancient, looks like 2017 -- before we switched to github actions for CI.  So maybe it doesn't run on my fork because my fork's master branch doesn't have the config for it?

I'm not sure if the fact that it runs on your fork is surprising to me or not.  You might be able to turn it off in your repository settings...  ahh, I found this screen:

<img width="842" alt="Screenshot 2024-05-27 at 10 05 21 am" src="https://github.com/cyrusimap/cyrus-imapd/assets/10985135/b27097ac-6420-428a-ace9-ed9ee7acbd43">

So you might want to choose the same "Disable actions" setting on your fork.  With my fork configured like that, I only get CI runs for PRs on the upstream repository, but not for all my own unfinished branches.  So I get notified if something that I think should work is broken, but I don't get hassled about everything else

**Comment by dilyanpalauzov** [comment]
> The master branch on my fork is ancient, looks like 2017 …

Can you try with the current master branch to see, if you get the same problem?

> I only get CI runs for PRs on the upstream repository, but not for all my own unfinished branches.

I only make PRs to the upstream repository.

I could disable all GitHub actions, and everybody could do the same.  Something is wrong with this pipeline, sending too many emails about non-existing failures.  Somebody who has understanding on how it works (I have no such understanding), is kindly asked to look at it and fix it.

**Comment by elliefm** [comment]
I've grabbed the assignment, cause I think some other changes I was already intending to make might also help here.  It'll be a few weeks before I can spend time on those changes though.

If you don't mind disabling actions on your repository, that should shut it up at least for now.  I can let you know to re-enable it once my changes are done.  In the meantime, if you _do_ want a CI run for a branch you're working on, it's enough to create a draft PR on upstream, because actions do run for draft PRs.  (I do this all the time myself.)
