### ISSUE TITLE
master kill too slow START commands

### ISSUE THREAD

**Issue by jcdelepine** [cyrusimap/cyrus-imapd#5044]
Hello,

Still on the way to migrate my backends from 3.2 to 3.8.

My solution to https://github.com/cyrusimap/cyrus-imapd/issues/4946 and https://github.com/cyrusimap/cyrus-imapd/issues/5043 is to use the --authoritative option to ctl_mboxlist in the START section of cyrus.conf.
That works, my 3.8 backends can start without reaching issue 4946.
But it's dangerous and it's an heavy and slow  command.

Too slow for one of my large backends. It takes 7mn on command line but get killed before end if launch in START.
Same problem occurs once getting back to 3.2 (still need one -a launch to get back his mailboxes).

My solution with 3.2 was to remove the -a after using the command line, but I have to use it on 3.8 backends.

Is there a way to say master not to kill slow commands ? 
Or should I remove the whole command from START and use it before starting cyrus ?

Sincerly,
     Jean Charles Delépine

**Comment by elliefm** [comment]
> Is there a way to say master not to kill slow commands ?

The START section is for jobs that must run to completion successfully before anything else starts.  If any of these jobs don't finish, then nothing else starts, and that's by design.  If any of them fail, master also exits with a failure message.  master does not and cannot know these jobs' internal state, so it cannot make decisions about whether or when they're safe to kill.

> Or should I remove the whole command from START and use it before starting cyrus ?

You should do this.
