### ISSUE TITLE
[2.5.9] ctl_mboxlist -v prints wrong directory

### ISSUE THREAD

**Issue by MASHtm** [cyrusimap/cyrus-imapd#52]
user has active part04 according to mailboxes.db:

```
$ ctl_mboxlist -d|grep vorscht5
user.vorscht5   0 part04 vorscht5   lr  
```

and 3 dead folders on other partitions:

```
/var/spool/imap/part03/D/user/vorscht5
/var/spool/imap/part04/D/user/vorscht5
/var/spool/imap/part08/D/user/vorscht5
/var/spool/imap/part09/D/user/vorscht5
```

ctl_mboxlist -v reports

```
'user.vorscht5' has a directory '/var/spool/imap/part09/D/user/vorscht5' but no DB entry
'user.vorscht5' has a directory '/var/spool/imap/part03/D/user/vorscht5' but no DB entry
'user.vorscht5' has a directory '/var/spool/imap/part04/D/user/vorscht5' but no DB entry
```

doing what it suggests would result in removal of vital data.

**Comment by MASHtm** [comment]
after removal of folders on part03, part08 and part09 it correctly doesn't report any of that user and is happy with the remaining part04

**Comment by MASHtm** [comment]
this also works with only two folders:
```
$ ctl_mboxlist -d|grep jungred4
user.jungred4	0 part09 jungred4	lrswipkxtecda	
```

folders available:
```
/var/spool/imap/part09/C/user/jungred4
/var/spool/imap/part14/C/user/jungred4
```

ctl_mboxlist -v output:
```
'user.jungred4' has a directory '/var/spool/imap/part09/C/user/jungred4' but no DB entry
```
exactly the wrong 50%

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
