### ISSUE TITLE
imap/http_caldav_js.h should be in the part of distfile

### ISSUE THREAD

**Issue by obache** [cyrusimap/cyrus-imapd#61]
`xxd` command is required to generate imap/http_caldav_js.h, but I can only find `xxd` as a part of _vim_.
It may be a popular editor and modular operating system such as Linux may have it a part of base system, but "files special tools are required to be generated" should be in distfile.

At least, _vim_ must be noted as a part of "Build Dependencies".

**Comment by brong** [comment]
@ksmurchison - sounds reasonable to add vim to build dependencies I guess, if it changes enough to not just commit it...

**Comment by elliefm** [comment]
I think it's pretty reasonable to pre-generate this file and include it in releases (which I think is what @obache is asking for?), so that people building from releases don't need xxd.  

I don't think we should commit it though, just pre-generate it when releasing.  (So people building from git would still need xxd... but I think people building from git already expect to need additional dependencies over and above what's needed to build from a release.)

Currently testing a commit to this effect, and will push it soon.
