### ISSUE TITLE
consider allowing numeric userids in auth_unix

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#670]
From: [Rob Siemborski](rjs3@andrew.cmu.edu)
Bugzilla-Id: 2447
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue has been sitting untouched for over ten years.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
