### ISSUE TITLE
cyr_virusscan will not be built if configure --with-clamav=DIR

### ISSUE THREAD

**Issue by obache** [cyrusimap/cyrus-imapd#68]
configure script accept location of installed clamav with "--with-clamav=DIR"

`AM_CONDITIONAL([HAVE_CLAMAV], [test "$with_clamav" = "yes"])`

$with_clamav should be changed to "yes" even if DIR is specified,
or test condition should be changed to `!= "no"`.

**Comment by elliefm** [comment]
I'm getting build failures on 2.5 now, unless I configure with --without-clamav.

Not yet sure what the cause is but it might be one of:

* I have clamav but the configure detection misses something
* I don't have clamav but the configure detection defaults to "yes" anyway
* something else?

Putting this here to remind me to investigate...

**Comment by obache** [comment]
If $with_clamav=yes (i.e. unless $with_clamav point to a directory), detection of clamav will not run now.

https://github.com/cyrusimap/cyrus-imapd/blob/bc5c9017290a70315d80e4e1eea28757e89402cc/configure.ac#L1036

**Comment by elliefm** [comment]
It only ever ran the detection if it was a directory -- that line has always been there.  I guess whoever wrote it in the first place used --with-clamav=DIR themselves, and didn't test anything else.

Basically the whole clamav detection block is junk and needs to be rewritten properly.  Happy to accept a patch or pull request; otherwise, I've taken the assignment, and I'll get to it in a little while.

**Comment by elliefm** [comment]
Looks like the intent was to "just use the system one" if --with-clamav is not a directory, and (on debian at least) you only need "-lclamav" to use the system one, so I guess that's how that came about.

I've just installed libclamav 0.99.2, and with it enabled, cyrus-imapd-2.5 doesn't build anyway -- errors in imap/cyr_virusscan.c.  But master builds okay, so there's probably some fixes in there to be backported.

**Comment by elliefm** [comment]
90b4efe looks like it might be the main commit to fix up cyr_virusscan.c, but it depends on mboxlist_findallmulti() which is not in 2.5

wip cherry-pick of it at https://github.com/elliefm/cyrus-imapd/commit/726e289d11b63b892451a1080558e1d34c012035

**Comment by elliefm** [comment]
I think this is all working properly now?

**Comment by obache** [comment]
2.5.11 is not.

1. In configure, `CMU_LIB_SUBDIR` is used but it is not defined yet there.
2.  `index_operatemailbox` is used in cyr_virusscan.c, but not declaerd anywhere.

**Comment by elliefm** [comment]
Doh, looks like I missed backporting a commit or two. :(

Digging into this now...

**Comment by elliefm** [comment]
Changes backported to cyrus-imapd-2.5 branch, it seems to work okay for me now.  Note that it no longer supports the --with-clamav=/path type of invocation though -- if your ClamAV is installed somewhere that pkgconfig can't find it, you'll need to set it in PKG_CONFIG_PATH.
