### ISSUE TITLE
TLS client authentication: allow optional client certificate

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#742]
From: [Goetz Babin-Ebell](goetz@shomitefo.de)
Bugzilla-Id: 2642
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
I don't know if Jeroen ever got anywhere with this, but it doesn't apply cleanly anymore.

```
patching file imap/tls.c
Hunk #1 FAILED at 578.
Hunk #2 FAILED at 673.
Hunk #3 FAILED at 685.
3 out of 3 hunks FAILED -- saving rejects to file imap/tls.c.rej
patching file imtest/imtest.c
Hunk #1 FAILED at 372.
Hunk #2 succeeded at 476 (offset -3 lines).
Hunk #3 FAILED at 515.
Hunk #4 FAILED at 536.
Hunk #5 FAILED at 684.
Hunk #6 FAILED at 2177.
Hunk #7 FAILED at 2294.
Hunk #8 FAILED at 2355.
Hunk #9 FAILED at 2503.
Hunk #10 FAILED at 2550.
9 out of 10 hunks FAILED -- saving rejects to file imtest/imtest.c.rej
patching file lib/imapoptions
Hunk #1 FAILED at 795.
Hunk #2 FAILED at 807.
2 out of 2 hunks FAILED -- saving rejects to file lib/imapoptions.rej
```

Also, the `tls_server_ca_file` imapd.conf setting that it tries to add already exists (though I don't know whether its purpose is the same).  So maybe this functionality has been implemented or merged already?

Closing this anyway, since one way or another, no-one seems to have cared about it in years.
