### ISSUE TITLE
Fails building on FreeBSD kernel with GNU userspace (PS_STRING defined but not usable)

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#878]
From: [Sven Mueller](cyrus@incase.de)
Bugzilla-Id: 2883
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by bogdro** [comment]
Apart from the fact that this issue may have already been fixed by the patch attached previously (~17 years ago...), I wanted to point the Cyrus project at Travis CI (https://travis-ci.com/). Free for open-source projects and supports building on FreeBSD (and Linux, macOS and Windows): https://docs.travis-ci.com/user/reference/freebsd/. Perhaps this would be enough to catch such problems.

**Comment by elliefm** [comment]
We just _stopped_ using Travis CI like a year ago, because their "free for open-source projects" required too much time in hand-holding it for non-trivial projects. 😅   I don't see any mention of kFreeBSD on their page anyway, which this issue was about.

https://github.com/cyrusimap/cyrus-imapd/issues/878#issuecomment-266645555 suggests this was already fixed before the 2.5 release, and if not, nobody's cared in 17 years.  I'm not sure why it's still open, but I don't think it needs to be.

**Comment by bogdro** [comment]
Hi.
**That** (about Travis) I obviously didn't know about...
You're the one who decides, no problem from my side. Anyway, just one less issue open, I guess :)
Thank you!
